### ISSUE TITLE
unexpected justification

### ISSUE THREAD

**Issue by tomek1024** [Kozea/WeasyPrint#1023]
In very seldom cases (combination of margin values, text, text settings and fonts) weasyprint incorrectly breaks the line. I attach the source as well the result. I use manual hyphenation.

html:
```html
<!doctype html>
<html lang='pl'>
  <head>
    <meta charset="UTF-8">
    <link href='style.css' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <p><strong>LIS&shy;BETH SALAN&shy;DER</strong> &amp; Aga wyszła spod prysz&shy;nica.</p>
  </body>
</html>
```

CSS:
```css
@font-face {
  font-family: "BookmanOld";
  src: url("https://zecer.elibri.com.pl/lte/fonts/BookmanOld/BookmanOld_R.ttf");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "BookmanOld";
  src: url("https://zecer.elibri.com.pl/lte/fonts/BookmanOld/BookmanOld_RB.ttf");
  font-weight: bold;
  font-style: normal;
}


@page {
  size: 160mm 235mm;
  margin-left: 21mm;
  margin-right: 21mm;
}


html { hyphens: manual; }

body {
  margin: 0;
  font-size: 14pt;
  font-family: BookmanOld;
}

p {
  text-align: justify;
  text-indent: 7mm;
  letter-spacing: -0.02em;
}
```

[test.pdf](https://github.com/Kozea/WeasyPrint/files/4042385/test.pdf)
