### ISSUE TITLE
Font weights missing when using @font-face rules

### ISSUE THREAD

**Issue by trthatcher** [Kozea/WeasyPrint#1028]
Hey!

Awesome project here - spectacular work.

Unfortunately, I've run into an issue with font-weights and I can't seem to resolve it. I'm working with a font that has several weights available (400, 500, 700), but the 500 weight does not appear to be used in the pdf output of WeasyPrint. It seems to fall back to the 400. When I open an HTML document in Chromium/Firefox, the 500 weight font is definitely rendering. I've gone through the older issues related to font, but didn't come across anything that seemed to be related.

I've downloaded these three fonts:
  - http://tug.ctan.org/fonts/roboto/opentype/Roboto-Regular.otf
  - http://tug.ctan.org/fonts/roboto/opentype/Roboto-Medium.otf
  - http://tug.ctan.org/fonts/roboto/opentype/Roboto-Bold.otf

and placed them in a `/fonts` folder. This is the HTML/CSS I'm using:

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        @font-face {
            font-family: "Roboto";
            font-style: normal;
            font-weight: 400;
            src: url(fonts/Roboto-Regular.otf) format("opentype");
        }

        @font-face {
            font-family: "Roboto";
            font-style: normal;
            font-weight: 500;
            src: url(fonts/Roboto-Medium.otf) format("opentype");
        }

        @font-face {
            font-family: "Roboto";
            font-style: normal;
            font-weight: 700;
            src: url(fonts/Roboto-Bold.otf) format("opentype");
        }

        p:before {
            content: 'Bacon ipsum dolor amet sausage rump tongue';
        }

        body {
            font: 16px serif;
        }

        .normal {
            font-family: 'Roboto';
            font-weight: 400;
        }

        .medium {
            font-family: 'Roboto';
            font-weight: 500;
        }

        .bold {
            font-family: 'Roboto';
            font-weight: 700;
        }
    </style>
</head>
<body>
<p></p>
<p class="normal"></p>
<p class="medium"></p>
<p class="bold"></p>
</body>
</html>
```

And here's the output of `weasyprint -i`:

```bash
System: Linux
Machine: x86_64
Version: #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019
Release: 5.0.0-32-generic

WeasyPrint version: 51
Python version: 3.7.4
Cairo version: 11510
Pango version: 14014
CairoSVG version: 2.4.2
```

Thanks in advance!

**Comment by trthatcher** [comment]
FYI, giving the medium font weight a different family name seems to be a work-around:

```css
@font-face {
    font-family: "Roboto Medium";
    font-style: normal;
    font-weight: 500;
    src: url(fonts/Roboto-Medium.otf) format("opentype");
}

.medium {
    font-family: 'Roboto Medium';
    font-weight: 500;
}
```

**Comment by liZe** [comment]
> Hey!

Hello!
 
> Awesome project here - spectacular work.

:blush:

> FYI, giving the medium font weight a different family name seems to be a work-around:

I’m pretty sure that the bug is caused by [this TODO](https://github.com/Kozea/WeasyPrint/blob/d2278aee69f94a6be6252467fc3c52b415a77958/weasyprint/fonts.py#L427-L428). I think that WeasyPrint uses the Roboto fonts installed on your system instead of the ones given in `@font-face` rules.

Could you try setting a unique `font-family`, different from `Roboto` (and from any font installed on your system), for the 3 font faces? If it works, then I’ll rename this issue and you will have to use this workaround for your document until it’s fixed :wink:.

**Comment by liZe** [comment]
> Could you try setting a unique `font-family`, different from `Roboto` (and from any font installed on your system), for the 3 font faces? If it works, then I’ll rename this issue and you will have to use this workaround for your document until it’s fixed .

@trthatcher Did you find the time to try this?

**Comment by liZe** [comment]
> @trthatcher Did you find the time to try this?

By the way, we have to ignore local fonts in this case. We also have to ignore some Fontconfig rules, as described in #1048.

**Comment by trthatcher** [comment]
Hey @liZe, thanks for checking in.

I'll get back to you tomorrow morning with some updates - I started testing a couple things but I unfortunately have to head out for the day. I also need to read over #1048. 

Sorry for the delay on my end.

**Comment by liZe** [comment]
> Sorry for the delay on my end.

No problem :wink:.

**Comment by trthatcher** [comment]
Okay, did some testing with the [Tillana](https://fonts.google.com/specimen/Tillana?selection.family=Tillana:400,500,600,700,800) font for the 400, 500, 600, 700 & 800 weights which are definitely not installed on my system. Here's the directory structure:

```bash
.
├── test.html
├── test.py
├── Tillana-Bold.ttf
├── Tillana-ExtraBold.ttf
├── Tillana-Medium.ttf
├── Tillana-Regular.ttf
└── Tillana-SemiBold.ttf
```
The file `test.html` is as follows:

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        @font-face {
            font-family: "Tillana";
            font-style: normal;
            font-weight: 400;
            src: url("Tillana-Regular.ttf") format("truetype");
        }

        @font-face {
            font-family: "Tillana";
            font-style: normal;
            font-weight: 500;
            src: url("Tillana-Medium.ttf") format("truetype");
        }

        @font-face {
            font-family: "Tillana";
            font-style: normal;
            font-weight: 600;
            src: url("Tillana-SemiBold.ttf") format("truetype");
        }

        @font-face {
            font-family: "Tillana";
            font-style: normal;
            font-weight: 700;
            src: url("Tillana-Bold.ttf") format("truetype");
        }

        @font-face {
            font-family: "Tillana";
            font-style: normal;
            font-weight: 800;
            src: url("Tillana-ExtraBold.ttf") format("truetype");
        }


        p:before {
            content: "Bacon ipsum dolor amet sausage rump tongue";
        }

        body {
            font: 16px mono;
        }

        .normal {
            font-family: "Tillana";
            font-weight: 400;
        }

        .medium {
            font-family: "Tillana";
            font-weight: 500;
        }

        .semibold {
            font-family: "Tillana";
            font-weight: 600;
        }

        .bold {
            font-family: "Tillana";
            font-weight: 700;
        }

        .extrabold {
            font-family: "Tillana";
            font-weight: 800;
        }
    </style>
</head>
<body>
<p></p>
<p class="normal"></p>
<p class="medium"></p>
<p class="semibold"></p>
<p class="bold"></p>
<p class="extrabold"></p>
</body>
</html>
```
I've attached the printed output for Firefox ([test-1-ff.pdf](https://github.com/Kozea/WeasyPrint/files/4144790/test-1-ff.pdf)), Chromium ([test-1-chromium.pdf](https://github.com/Kozea/WeasyPrint/files/4144791/test-1-chromium.pdf)) and WeasyPrint ([test-1-wp.pdf](https://github.com/Kozea/WeasyPrint/files/4144793/test-1-wp.pdf)). It looks like the 500 weight is falling back to the 400.

**Comment by trthatcher** [comment]
For whatever reason (ex. I could be blind and missing something obvious), when I try to replicate the above using a script, WeasyPrint doesn't seem to be finding the Tillana fonts in the same directory as the script referenced by the `font-face` rule. Here's my script:

```python
# -*- coding: utf-8 -*-
from weasyprint import CSS, HTML
from weasyprint.fonts import FontConfiguration

HTML_DOC = '''
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<p></p>
<p class="normal"></p>
<p class="medium"></p>
<p class="semibold"></p>
<p class="bold"></p>
<p class="extrabold"></p>
</body>
</html>
'''

CSS_DOC = '''
@font-face {
    font-family: "Tillana";
    font-style: normal;
    font-weight: 400;
    src: url("Tillana-Regular.ttf") format("truetype");
}

@font-face {
    font-family: "Tillana";
    font-style: normal;
    font-weight: 500;
    src: url("Tillana-Medium.ttf") format("truetype");
}

@font-face {
    font-family: "Tillana";
    font-style: normal;
    font-weight: 600;
    src: url("Tillana-SemiBold.ttf") format("truetype");
}

@font-face {
    font-family: "Tillana";
    font-style: normal;
    font-weight: 700;
    src: url("Tillana-Bold.ttf") format("truetype");
}

@font-face {
    font-family: "Tillana";
    font-style: normal;
    font-weight: 800;
    src: url("Tillana-ExtraBold.ttf") format("truetype");
}


p:before {
    content: "Bacon ipsum dolor amet sausage rump tongue";
}

body {
    font: 16px mono;
}

.normal {
    font-family: "Tillana";
    font-weight: 400;
}

.medium {
    font-family: "Tillana";
    font-weight: 500;
}

.semibold {
    font-family: "Tillana";
    font-weight: 600;
}

.bold {
    font-family: "Tillana";
    font-weight: 700;
}

.extrabold {
    font-family: "Tillana";
    font-weight: 800;
}
'''


if __name__ == '__main__':
    font_config = FontConfiguration()

    test_css  = CSS(string=CSS_DOC, font_config=font_config)
    test_html = HTML(string=HTML_DOC)

    test_html.write_pdf('test-2.pdf',
                        stylesheets=[test_css],
                        font_config=font_config)
```

Then I'm just running:

```bash
python3 test.py
```
Now I'm not certain what happened when I first posted the issue.

**Comment by Tontyna** [comment]
You should see warnings like that:

```
Ignored `src: url("Tillana-Regular.ttf") format("truetype")` at 6:5, Relative URI reference without a base URI: 'Tillana-Regular.ttf'.
```

Alas, provide a `base_url`, e.g.:

```python
import os

base_url =  os.path.dirname(os.path.abspath(__file__)) 

test_html.write_pdf('test-2.pdf',
                        stylesheets=[test_css],
                        font_config=font_config,
                        base_url=base_url
)
```

**Comment by trthatcher** [comment]
Yep, I am blind... not sure how I missed the `base_url` param. Thanks @Tontyna - that solved the issue.

**Comment by liZe** [comment]
So, we have a bug that’s not related to Fontconfig configurations. I’ve open a new issue (#1059) for that new problem, and changed the title of this issue to reflect the original problem.

**Comment by fabriceci** [comment]
I have a similar issue, I don't know if I should create a new issue.

I use @fontface with base64 embedded font in the css (not present in my system). When the pdf is generated it appears like a box in the generated PDF (HTML work well in browsers). As the font is embedded, you can test this easily : https://pastebin.com/hHjjz5C6

**Comment by CedricCook** [comment]
Hi, just wanted to say that this bug (`font-weight: 500` interpreted as `font-weight: 400` in weasyprint) is still present in WeasyPrint 52.5 atleast, and that the solution is still at the moment to rename the 500-weight font as a different family, and then use that family in some cases. 

Here's a small example (pseudo code-ish)
```css
@font-face {
    font-family: 'Roboto';
    src: url("fonts/Roboto/Roboto-Regular.ttf") format('ttf'),
        url("'fonts/Roboto/Roboto-Regular.woff2") format('woff2'),
    font-weight: 400;
    font-style: normal;
}
@font-face {
    font-family: 'Roboto Medium';  /* https://github.com/Kozea/WeasyPrint/issues/1028 */
    src: url("'fonts/Roboto/Roboto-Medium.ttf") format('ttf'),
        url("'fonts/Roboto/Roboto-Medium.woff2") format('woff2')
    font-weight: 500;
    font-style: normal;
}

.normal-text {
    font-family: 'Roboto';
    font-weight: 400;
}

.medium-style-text {
    font-family: 'Roboto Medium';
    font-weight: 500;
}
```

**Comment by aleho** [comment]
Is font selection within a family supposed to work at all?

E.g. this will result in very strange font selection (seemingly random):

```css
@font-face {
    font-family: 'MyFont';
    font-weight: 100 200;
    font-style: normal;
    src: url('./MyFont_Light.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont';
    font-weight: 100 200;
    font-style: italic;
    src: url('./MyFont_LightItalic.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont';
    font-weight: 300 400;
    font-style: normal;
    src: url('./MyFont_Book.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont';
    font-weight: 300 400;
    font-style: italic;
    src: url('./MyFont_BookItalic.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont';
    font-weight: 500 600;
    font-style: normal;
    src: url('./MyFont_Medium.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont';
    font-weight: 500 600;
    font-style: italic;
    src: url('./MyFont_MediumItalic.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont';
    font-weight: 700;
    font-style: normal;
    src: url('./MyFont_Bold.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont';
    font-weight: 700;
    font-style: italic;
    src: url('./MyFont_BoldItalic.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont';
    font-weight: 800 900;
    font-style: normal;
    src: url('./MyFont_Black.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont';
    font-weight: 800 900;
    font-style: italic;
    src: url('./MyFont_BlackItalic.otf') format('opentype');
}
```


Whereas using a separate name for each style, the correct fonts are selected. Problem with this is, we cannot use font-weights or styles anywhere and have to explicitly specify the font family:

```css
@font-face {
    font-family: 'MyFont Light';
    font-weight: 100 200;
    font-style: normal;
    src: url('./MyFont_Light.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont Light Italic';
    font-weight: 100 200;
    font-style: italic;
    src: url('./MyFont_LightItalic.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont Book';
    font-weight: 300 400;
    font-style: normal;
    src: url('./MyFont_Book.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont Italic';
    font-weight: 300 400;
    font-style: italic;
    src: url('./MyFont_BookItalic.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont Medium';
    font-weight: 500 600;
    font-style: normal;
    src: url('./MyFont_Medium.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont Medium Italic';
    font-weight: 500 600;
    font-style: italic;
    src: url('./MyFont_MediumItalic.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont Bold';
    font-weight: 700;
    font-style: normal;
    src: url('./MyFont_Bold.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont Bold Italic';
    font-weight: 700;
    font-style: italic;
    src: url('./MyFont_BoldItalic.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont Black';
    font-weight: 800 900;
    font-style: normal;
    src: url('./MyFont_Black.otf') format('opentype');
}

@font-face {
    font-family: 'MyFont Black Italic';
    font-weight: 800 900;
    font-style: italic;
    src: url('./MyFont_BlackItalic.otf') format('opentype');
}
```
