### ISSUE TITLE
Ignore any section in my template to export

### ISSUE THREAD

**Issue by antuaneacion** [Kozea/WeasyPrint#1034]
hello everyone, is there any way to ignore any section of my template? for example, when I generate the pdf I just want to export the report area, that is, only the table, not the form or the main menu

**Comment by Tontyna** [comment]
Hide the sections you wanna ignore via css:

```css
@media print { 
  .dontprint {
    display: none;
  }
}
```
