### ISSUE TITLE
Tables in tables does not go to the other page

### ISSUE THREAD

**Issue by pax0r** [Kozea/WeasyPrint#1040]
Hi,
I am trying to convert Heroku e-mail with receipts to PDFs using WeasyPrint. 
Sadly Heroku HTML is not so well made one and it contains multiple tables inside another tables. 

The biggest issue I have is that some parts
 of the tables are "lost" and not printed in the result PDF. 

Input HTML:
[heroku-invoice.html.txt](https://github.com/Kozea/WeasyPrint/files/4107857/heroku-invoice.html.txt)
Output PDF:
[convert-test.pdf](https://github.com/Kozea/WeasyPrint/files/4107856/convert-test.pdf)

As you can see some of the invoice lines, subtotal and total parts of the table with amounts are lost.
Is there any way to force Weasyprint to split tables like that on multiple pages?

I've tried to set some `break-*` css properties attached to the HTML but without any succcess.

**Comment by liZe** [comment]
Hi!

> Sadly Heroku HTML is not so well made one and it contains multiple tables inside another tables.

Yes, and that’s the reason why this table is not split: the whole table is inside another cell from another table. As explained in #36, WeasyPrint is currently unable to split table cells, and thus unable to split this table.

Of course, there are workarounds: you can add a stylesheet to make tables render as normal blocks. Here’s a quick-and-dirty stylesheet you can use:
```css
  table, tbody, tr, td {
    display: block;
  }
  table table table table {
    margin: 1em 0 !important;
  }
  table table table table tr {
    display: flex;
  }
  table table table table td {
    width: 50%;
  }
```

I close this issue as it’s a duplicate of #36, but feel free to answer if you need more information about the stylesheet (or to tell that everything works fine :wink:).
