### ISSUE TITLE
Position of list marker is wrong after a page break

### ISSUE THREAD

**Issue by craigbass76** [Kozea/WeasyPrint#1058]
I'm not sure what the problem is here. When an ordered list is going over a page break, the text is bumped up a bit. See list item #4. 
![list-over-page-break](https://user-images.githubusercontent.com/12818479/74262103-42709280-4cca-11ea-848e-e49be4ae8e45.png)

I was trying to manually put a page break in there, but then this item#4 kept becoming a new Item#1.

**Comment by craigbass76** [comment]
Is there a workaround for the time being?

**Comment by craigbass76** [comment]
If it helps, it looks like this only happens with the list item in question is more than a line long.

**Comment by GiovanniSalmeri** [comment]
Some problem here. I have produced a minimal example: the problem seems to occur (both with ordered and unordered lists) when the item contains a paragraph:

```html
<li><p>List item</p></li>
```

but not if the item cointains only text:

```html
<li>List item</li>
```

Perhaps this will help to hunt down the bug?

**Comment by NicHub** [comment]
I got the same problem. If an `<ol>` or an `<ul>` contains `<li><p>...</p></li>` elements, then the bullet or the number is not aligned on the first list item after a page break.

I wonder if it is related to this behavior which looks like a bug: On a document without custom CSS, the first page top margin is bigger than all other top margins in the document and the difference is the height of one line.

Anyway, here is a (quite convoluted) workaround. It seems to work even with nested lists. I usually use it to replace bullets with the characters I want in `<ul>`. This CSS removes the actual number or bullet and replaces it with a counter or a character.


```css

<style>
    ol,
    ul {
        counter-reset: list-item-counter;
        list-style-type: none;
    }

    ol li p,
    ul li p {
        counter-increment: list-item-counter;
        text-indent: -2.0rem; /* must be equal to -width (see below) */
    }

    ol li p::before,
    ul li p::before {
        display: inline-block;
        left: -0.16rem;
        margin: 0;
        padding: 0;
        position: relative;
        text-align: right;
        width: 2.0rem;
    }

    ol li p::before {
        content: counter(list-item-counter)".";
    }

    ul li p::before {
        content: "•";
    }

</style>
```
