### ISSUE TITLE
target-counter can’t find counters in page margins when they have not been used in page content

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#1062]
The current implementation lacks support the `url()` functio.

Example for injecting a custom total of pages counter where the end of a document is marked by a `div#end`:

```
content: "Page " counter(page) " of " target-counter(url("#end"), page);
```

**Comment by liZe** [comment]
The problem doesn’t come from `url()`, it’s caused by something else: `target-counter` can’t find counters in page margins when they have not been used in page content.

This example doesn’t work:

```css
body { counter-reset: section }
@page{ @bottom-center { content: target-counter(url(#end), page) } }
```

but this example does:
```css
body { counter-reset: section }
@page{ @bottom-center { content: target-counter(url(#end), page) } }
div::before { content: target-counter(url(#end), page) }
```
