### ISSUE TITLE
Incorrect use of local font instead of using remote font referenced by @font-face rule

### ISSUE THREAD

**Issue by gentooboontoo** [Kozea/WeasyPrint#1073]
I am trying to render a page including the following style rules:

```css
@font-face {
  font-family: 'Asap';
  font-style: normal;
  font-weight: 400;
  src: local('Asap Regular'), local('Asap-Regular'), url(https://fonts.gstatic.com/s/asap/v11/KFOoCniXp96ayzse5Q.ttf) format('truetype');
}
```
The PDF is rendered with an incorrect font because the font `Asap Regular` is missing on my system and WeasyPrint does not try to use the remote font reference.

After having done some digging on my Linux system, when _Fontconfig_ tries to match a local font with `postscriptname` and `fullname` properties (as done by WeasyPrint) and does not find it, it returns a matching pattern with the `postscriptname` property set to the best matching font (as expected) but the `fullname` property is still set to the same value than the requested font.

https://github.com/Kozea/WeasyPrint/blob/d6ef067deb3234c36a5e364fb20711705e820094/weasyprint/fonts.py#L327-L334

For instance, if _Fontconfig_ tries to match 'Asap Regular` as font and it is missing, it returns the following properties:

```
# Equivalent to WeasyPrint code
λ fc-match -v ":fullname=Asap Regular:postscriptname=Asap Regular"
Pattern has 36 elts (size 48)
        family: "Adobe Utopia"(s)
        style: "Regular"(s)
        stylelang: "en"(s) "en"(s)
        fullname: "Asap Regular"(s)
        slant: 0(i)(s)
        weight: 80(f)(s)
        width: 100(f)(s)
        size: 12(f)(s)
        pixelsize: 12(f)(s)
        foundry: "Adobe"(w)
        antialias: False(w)
        hintstyle: 1(i)(w)
        hinting: True(s)
        verticallayout: False(s)
        autohint: False(s)
        globaladvance: True(s)
        file: "/usr/share/fonts/75dpi/UTRG__12-ISO8859-1.pcf.gz"(w)
        index: 0(i)(w)
        outline: False(w)
        scalable: False(w)
        dpi: 75(f)(s)
        scale: 1(f)(s)
        charset:
        0000: 00000001 ffffffff ffffffff 7fffffff 00000000 ffffffff ffffffff ffffffff
(w)
        lang: aa|ay|bi|br|ch|da|de|en|es|eu|fj|fo|fur|fy|gd|gl|gv|ho|ia|id|ie|io|is|it|lb|mg|nb|nds|nl|nn|no|nr|oc|om|pt|rm|sma|smj|so|sq|ss|st|sv|sw|tl|ts|uz|vo|wa|xh|yap|zu|an|fil|ht|jv|kj|kwm|li|ms|ng|pap-an|pap-aw|rn|rw|sc|sg|sn|su|za(s)
        fontversion: 0(i)(s)
        fontformat: "PCF"(w)
        embeddedbitmap: True(s)
        decorative: False(s)
        namelang: "en"(s)
        prgname: "fc-match"(s)
        postscriptname: "Adobe-Utopia"(s)
        color: False(w)
        symbol: False(s)
        variable: False(s)
        pixelsizefixupfactor: 1(f)(w)
        scalingnotneeded: True(w)
```

The exact font is not found but WeasyPrint follows anyway the happy path and use the substituted local font instead of retrieving the remote font referenced in the `@font-face` rule. WeasyPrint thinks the exact font is found because the resulting `fullname` value is the same as the requested one.

I don't know if this is a bug from WeasyPrint, Fontconfig or my system's font configuration.

**Comment by skpaz** [comment]
Resurrecting this old thread because I've encountered the same issue with weasyprint v63.1. It seems to have been introduced between 62.3 (no issue) and 63.1 (issue started) - I can reproduce the issue easily.

In our case, the style sheet is remote, but it contains CSS at-rules the same as OP, and the same result occurs.

```txt
INFO: __init__.py:162 (__init__): Step 1 - Fetching and parsing HTML - cover.html
INFO: __init__.py:289 (__init__): Step 2 - Fetching and parsing CSS - https://example.com/web/fonts/inter.css
INFO: __init__.py:289 (__init__): Step 2 - Fetching and parsing CSS - CSS string
WARNING: __init__.py:188 (validation_error): Ignored `text-shadow: 2px 2px 3px rgba(0,0,0,0.5),4px 4px 5px rgba(255,255,255,0.5),` at 20:7, unknown property.
INFO: __init__.py:69 (__init__): Step 3 - Applying CSS
INFO: document.py:242 (_build_layout_context): Step 4 - Creating formatting structure
INFO: page.py:907 (make_all_pages): Step 5 - Creating layout - Page 1
INFO: __init__.py:118 (generate_pdf): Step 6 - Creating PDF
INFO: __init__.py:228 (generate_pdf): Step 7 - Adding PDF metadata
```

Here is the content of the style sheet:

```css
/* inter-regular - latin */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('/web/fonts/inter/inter-v3-latin-regular.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('/web/fonts/inter/inter-v3-latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('/web/fonts/inter/inter-v3-latin-regular.woff2') format('woff2'), /* Super Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-regular.woff') format('woff'), /* Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-regular.ttf') format('truetype'), /* Safari, Android, iOS */
       url('/web/fonts/inter/inter-v3-latin-regular.svg#Inter') format('svg'); /* Legacy iOS */
}

/* inter-500 - latin */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: url('/web/fonts/inter/inter-v3-latin-500.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('/web/fonts/inter/inter-v3-latin-500.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('/web/fonts/inter/inter-v3-latin-500.woff2') format('woff2'), /* Super Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-500.woff') format('woff'), /* Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-500.ttf') format('truetype'), /* Safari, Android, iOS */
       url('/web/fonts/inter/inter-v3-latin-500.svg#Inter') format('svg'); /* Legacy iOS */
}

/* inter-600 - latin */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url('/web/fonts/inter/inter-v3-latin-600.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('/web/fonts/inter/inter-v3-latin-600.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('/web/fonts/inter/inter-v3-latin-600.woff2') format('woff2'), /* Super Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-600.woff') format('woff'), /* Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-600.ttf') format('truetype'), /* Safari, Android, iOS */
       url('/web/fonts/inter/inter-v3-latin-600.svg#Inter') format('svg'); /* Legacy iOS */
}

/* inter-700 - latin */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url('/web/fonts/inter/inter-v3-latin-700.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('/web/fonts/inter/inter-v3-latin-700.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('/web/fonts/inter/inter-v3-latin-700.woff2') format('woff2'), /* Super Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-700.woff') format('woff'), /* Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-700.ttf') format('truetype'), /* Safari, Android, iOS */
       url('/web/fonts/inter/inter-v3-latin-700.svg#Inter') format('svg'); /* Legacy iOS */
}
```

Another, local style sheet calls `html, body {font-family: inter, sans-serif;}`, but it fails to use the designated font and instead defaults to a local sans-serif font. In this case it's Verdana. I can also reproduce the issue by trying to call the at-rule font directly via `style`.

```txt
% pdffonts cover.pdf 
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
IETZIE+Verdana-Bold                  CID TrueType      Identity-H       yes yes yes     15  0
VMAKMM+Verdana-Bold-Italic           CID TrueType      Identity-H       yes yes yes     19  0
```

On my local machine it defaults to Verdana, but in our build pipelines on Ubuntu it uses DejaVu Math TeX Gyre for some insane reason ... obviously not a sans-serif font.
