### ISSUE TITLE
Changing header on reports by defining a html tag/id #request

### ISSUE THREAD

**Issue by bjornasm** [Kozea/WeasyPrint#1140]
Right now, when I use the reports template, the upper rightmost header text is the same as the chapter` <h2>` header text. However, I rather want an uniform header text (f.ex date and company name). It would be great if you could define a `<p class="header">headertext</p> `that was invisible, but was put in place as the header text by WeasyPrint.

**Comment by liZe** [comment]
Hi!

I think that what you want is [running elements](https://www.w3.org/TR/css-gcpm-3/#running-elements), and … it’s already in WeasyPrint :wink:.

Let me know if it works for you!

**Comment by Tontyna** [comment]
[Running elements](https://drafts.csswg.org/css-gcpm/#running-elements) is what you are looking for:

```css
  @page { 
    @top-center { content: element(myheader) }
  }
 .header { 
    position: running(myheader); 
 }
```
