### ISSUE TITLE
Bookmarks repeat on every page

### ISSUE THREAD

**Issue by arikrupnik** [Kozea/WeasyPrint#1145]
I'm formatting an XML file. I want to generate an index, but for some reason I'm getting an entry for every section on each page. What am I doing wrong? Using Weasyprint 51 and Python 3.7.5 on Linux.

```xml
<doc>
  <section heading="1976">
    <section heading="Cemetery">
      <scene>EXT. CEMETERY -- NIGHT</scene>
      Rederik, now 28, lies behind a GRAVESTONE. He has a beard now, but is growing thinner on the top. He squints through a tree branch he's holding in front of his face.
```
CSS snippet:

```css
section { bookmark-level: 1; bookmark-label: attr(heading); }
section > section { bookmark-level: 2; }
section > section > section { bookmark-level: 3; }
```
![Screenshot_2020-06-17_12-18-50](https://user-images.githubusercontent.com/1756197/84928901-bb2a9580-b094-11ea-8306-0e9d55365ae8.png)
