### ISSUE TITLE
Table inner borders are to wide

### ISSUE THREAD

**Issue by EugenMayer** [Kozea/WeasyPrint#1181]
When using table borders like 

```html
<table border='2'>
<tr><td>test1</td><td>test2</td><td>test3</td></tr>
<tr><td>test4</td><td>test5</td><td>test6</td></tr>
<table>
```

with that css 

```css
  table {
    border-color: black;
    border-style: solid;
    border-collapse: collapse;
    box-sizing: border-box;
  }
```

A browser would display a 2px wide outer border, while the inner borders are 1px. This does not work for weasyprint, the border is always the same for inner and outer border.

Also weasyprint would display a border, even if `border=0` is used, which a browser does not.

currently we are hacking this naivly using 

```css 
  table[border='0'] {
    &, td {
      border-color: transparent;
      border-style: none;
      border-collapse: collapse;
      box-sizing: border-box;
    }
  }

  table[border='2'],table[border='3'],table[border='4'] {
    td {
      border-width: 1px;
    }
  }
```

we are using v51
