### ISSUE TITLE
pseudo class with height as calc() doesn't seem to work

### ISSUE THREAD

**Issue by Skylsmoi** [Kozea/WeasyPrint#1207]
Hi,
I'm using python 3.7 and WeasyPrint==51

My issue is to render this:
``` css
.myClass::after {
    content: '';
    position: absolute;
    border: 1px solid #000;
    border-right-width: 0;
    border-top-width: 0;
    left: 10px;
    top: calc(0% - 15px);
    width: 7px;
    height: calc(50% + 15px);
    line-height: 16px;
    color: #000;
}
```

which, using border-left and border-bottom, should render something looking like an L.

On my html render, it works well, but on the pdf render, the border-left isn't rendered.

To fix it, I must not use the function `calc()` in the `height` rule.

It seems there is something not working with the height as calc() in a pseudo class.
The issue is the same with ::before and ::after
