### ISSUE TITLE
Handle var function in properties with multiple values

### ISSUE THREAD

**Issue by oussama-he** [Kozea/WeasyPrint#1219]
I'm using weasyprint in one of my projects and I would like to use CSS variables but they don't work correctly.
I have these rules like these in my `style.css`:
```css
:root {
  --primary-color: #2ea44f;
}

.table thead {
    background-color: var(--primary-color);
    color: #fff;
    text-align: left;
}

.table tbody tr:last-child {
    border-bottom: 2px solid var(--primary-color);
}
```
The rule `.table thead {...}`  works normally and this rule `.table tbody tr:last-child{...}` doesn't work and I get a message in the terminal:
```
WARNING: Ignored `border-bottom: 2px solid var(--primary-color)` at 90:5, invalid value.
```

Any help, please?
Thank you in advance.
