### ISSUE TITLE
Support font-variant: small-caps approximation

### ISSUE THREAD

**Issue by blagasz** [Kozea/WeasyPrint#123]
Hi,

It is written in the documentation that I should report as a bug if some CSS 2.1 feature is not working. I found that the `font-variant: small-caps` CSS is not working (it works in the browser, but not in the rendered PDF).

Hope this helps, regards, Sz'

**Comment by liZe** [comment]
After playing with Pango and fontconfig, I now know that fontconfig is able to generate false small-caps, italic and bold fonts. I don't know exactly how it works, but I suppose that it could be included in WP. I'm ready to help anybody interested in this feature :smile:.

**Comment by manuthema** [comment]
Hi liZe. I´m interesting in this feature

**Comment by liZe** [comment]
> Hi liZe. I´m interesting in this feature

Good to know!

> After playing with Pango and fontconfig, I now know that fontconfig is able to generate false small-caps, italic and bold fonts. I don't know exactly how it works, but I suppose that it could be included in WP. I'm ready to help anybody interested in this feature .

Well… It's definitely true for "faux" bold and italic, and it's already included in WeasyPrint. But unfortunately, I can't find anything about small caps :cry:. I don't know if it was just a dream, if I've seen small-caps where there was just bold and italic, or if I had found something else… If anyone knows anything about that, I'd be glad to learn!

**Comment by bpj** [comment]
``````css
/*** fake small-caps to overcome bug ***/

.sc, .smallcaps, .small-caps {
  /* font-variant: small-caps; */
  text-transform: uppercase; font-size: 75%; 
}

/* force uppercase inside faked small-caps:
  <span class="sc"><span class="scu">C</span>aesar</span>
*/
.scu {
  /* font-variant: small-caps; */
  text-transform: uppercase; font-size: 133%; 
}

/* .usc = uppercase to small-caps:
   <span class="usc">SMALL CAPS</span>
   <span class="usc"><span class="scu">C</span>AESAR</span>
*/
.usc {
  /* text-transform: lowercase; font-variant: small-caps; */
  text-transform: uppercase; font-size: 75%;
}
``````

Fake small caps may be a crime against typography, but what can you do when the style guide demands them?
