### ISSUE TITLE
Wrong text orientation with column flex direction

### ISSUE THREAD

**Issue by ayum** [Kozea/WeasyPrint#1327]
I use:
```sh
> weasyprint --version
WeasyPrint version 52.4
```

Command:
```sh
> echo "<div><hr></div>" | weasyprint -s stylesheet.css - test.pdf
```

CSS file "stylesheet.css":
```css
div {
    display: flex;
    flex-direction: column;
}

hr {
    text-align: center;
    border: none;
}

hr::after {
    content: '* * *';
}
```

I expect: asterisks would be oriented horizontally as in all browser user-agents.

Actual result: asterisks oriented vertically.
