### ISSUE TITLE
Weasyprint not recognizing my font: OCR A

### ISSUE THREAD

**Issue by mgs4ff** [Kozea/WeasyPrint#1380]
```css
@font-face {
    font-family: 'OCR-A';
    src: url('../../fonts/ocra/OcrA.ttf') format('ttf'),
      url('../../fonts/ocra/OCRA Medium.ttf') format('ttf'),
      url('../../fonts/ocra/OCRA Regular.ttf') format('ttf'),
      url('../../fonts/ocra/OCRA-Alternate.otf') format('otf');
    font-weight: 200;
    font-style: normal;
  }
```

`style="font-family: OCR-A !important;"`

```python
    font_config = FontConfiguration()
    css = CSS(string='''    
    @font-face {
        font-family: 'OCR-A';
        src: url('file:///fonts/ocra/OcrA.ttf') format('ttf'),
        url('file:///fonts/ocra/OCRA Medium.ttf') format('ttf'),
        url('file:///fonts/ocra/OCRA Regular.ttf') format('ttf'),
        url('file:///fonts/ocra/OCRA-Alternate.otf') format('otf');
        font-weight: 200;
        font-style: normal;
    }
    ''', font_config=font_config)
```

I've researched this a lot online and followed all of the advice given, however the output of my PDF is still not in the correct font.  Im using weasyprint 52.4 and just trying to implement a section of the page with OCR-A font.  Any help on this would be appreciated
