### ISSUE TITLE
Background Color on Pages with a Bleed Property do not fill the whole page

### ISSUE THREAD

**Issue by azettl** [Kozea/WeasyPrint#1446]
If you use the CSS bleed property in combination with a background color, the color is not filling the whole page, see:

![image](https://user-images.githubusercontent.com/644570/133801001-29a06091-a788-449f-969d-dae3ff1891d4.png)

The sample code is the following:

HTML:
```html
<div class="break"></div>
<span class="head">
    <b>Max Mustermann</b>
    <br />
    a fancy and long title
</span>
<br />
max.mustermann@example.com
<br />
Mobile +49 123 4567 8901
<br />
www.example.com
<br />
<span class="foot">
    Example Company
    <br />
    Busystreet 5 &middot; 00001 Gotham
</span>
```

CSS:
```css
@page{
    size:3.5in 2in;
    marks:crop;
    bleed:0.125in;
    margin:0.25in;
} 

@page:first{
    background:rgb(188, 11, 6);
    background-image:url(https://www.html2pdf.guru/assets/img/html2pdf.guru.png);
    background-position: center;
    background-repeat: no-repeat;
    margin:0;
}

body{
    font-size:10pt;
}

b{
    color:rgb(188, 11, 6);
    font-size:1.5rem;
}

.head{
    display:inline-block;
    margin-bottom: .5rem;
}

.foot{
    display:inline-block;
    margin-top: .75rem;
    border-left:.25rem solid rgb(188, 11, 6);
    padding-left:.5rem;
}

.break{
    page-break-after: always;
    break-after: always;
}
```

You can see the issue here https://printcss.live/JX7axvrdyv
