### ISSUE TITLE
target-counter(attr(href), page) renders “0” instead of the actual page number

### ISSUE THREAD

**Issue by devopsix** [Kozea/WeasyPrint#1491]
`target-counter(attr(href), page)` seems to render “0” instead of the actual page number if the element into whose `::after` it is rendered has `display: flex;` set.

Given this markup and styles:

toc.html

```html
<!DOCTYPE html>
<html>
<head>
    <link href="toc.css" rel="stylesheet" />
</head>
<body>
    <nav id="toc1">
        <ul><li><div><a href="#article-1">...</a></div></li></ul>
    </nav>
    <nav id="toc2">
        <ul><li><div><a href="#article-1">...</a></div></li></ul>
    </nav>
    <nav id="toc3">
        <ul><li><div><a href="#article-1">...</a></div></li></ul>
    </nav>
    <article>
        <h1 id="article-1">Article 1</h1>
    </article>
</body>
</html>
```

toc.css

```css
article {
    page-break-before: always;
}

li a::before {
    content: target-text(attr(href));
}
li a::after {
    content: target-counter(attr(href), page);
}

#toc2 li a {
    display: flex;
}

#toc3 li div {
    display: flex;
}
```

When rendering this to PDF with Weasyprint 53.3 (`weasyprint toc.html toc.pdf`) then the output document should contain 3 times the same link text.

Expected output:

![expected-output](https://user-images.githubusercontent.com/58369032/141148553-91f98fb5-db2b-40e1-b249-c1c2274b4e9c.png)

But for the second link text, “0” is rendered for the target page counter instead of “2”.

Actual output:

![actual-output](https://user-images.githubusercontent.com/58369032/141150616-cd717d0c-00b6-407b-98f1-a5933ddb2930.png)
