### ISSUE TITLE
Selector Pseudo Function closing 

### ISSUE THREAD

**Issue by Dexus** [Kozea/WeasyPrint#1516]
``` 
xhtml2pdf.w3c.cssParser.CSSParseError: Selector Pseudo Function closing ')' not found:: (':not( ', ':local-link )):after')
```

```CSS

            a:not( :local-link ):after {
                content: " <" attr(href) "> ";
            }
```
