### ISSUE TITLE
Fonts not used when included through the CSS object

### ISSUE THREAD

**Issue by qwenger** [Kozea/WeasyPrint#1518]
Hi,

Thanks for this package!

I have an issue when including stylesheets through the API, in `write_pdf`: further inclusion of font files does not seem to be taken in account when using a CSS object.

MWE:

`build.py`:
```python
from weasyprint import HTML, CSS
h = HTML("in.html")
h.write_pdf("out1.pdf", stylesheets=["in.css"])
h.write_pdf("out2.pdf", stylesheets=[CSS(filename="in.css")])
h.write_pdf("out3.pdf", stylesheets=[CSS(string=open("in.css").read())])
```

`in.html`:
```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	</head>
	<body>
		<p>test</p>
	</body>
</html>
```

`in.css`:
```css
@font-face {
	font-family: "test";
	src: url("path/to/some/file.ttf");
}
p {
	font-family: "test";
	color: red;
}
```

Once you run `build.py`, you will get `out1.pdf`, `out2.pdf` and `out3.pdf`. All contain "text" in red (which means that `in.css` was used), but only `out1.pdf` uses the specified font.
