### ISSUE TITLE
absolute positioned footer not completely displayed

### ISSUE THREAD

**Issue by hiaselhans** [Kozea/WeasyPrint#1591]
Thanks for this great library! We are using it since years and it's working great.

I noticed that beginning with version 54.0 our footer wasn't displayed correctly. Only a small fraction of it was visible. I will try to make a small reproducer, but here are the rough details:

``` html
<html>
  <body>
    <div class="footer">
        <p>el1</p>
        <p>el2</p>
        <p>el3</p>
        <p>el4</p>
    </div>
  </body>
</html>
```

``` css
@page {
  size: A4;
  margin: 0;
  margin-bottom: 4cm;
}

div.footer {
  position: fixed;
  top: 100%;
  height: 4cm;
  display: flex;
  flex-direction: row;
}
```

problem is that as of 54.0 only one or two or a random number of childs from footer are displayed.
