### ISSUE TITLE
`counter-increment` is not working

### ISSUE THREAD

**Issue by ritiksoni00** [Kozea/WeasyPrint#1599]
```html
<div style="--incr: 4">a</div>
<div style="--incr: 6">b</div>
<div style="--incr: 4">c</div>
<div style="--incr: 4">d</div>
<div style="--incr: 4">e</div>
<div style="--incr: 4">f</div>
<div style="--incr: 4">g</div>


```

```css
div {
  counter-increment: sum var(--incr);
}

div::after {
  content: "-" counter(sum)
}
```
not supported counter-increment. 

the sum is always zero using weasyprint. it should be incremented as in the given example.

 [example](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0sxhAGhADMBLGXVAbVADsBDAWwjUwAt56p8RYB7axfswA8SYgDcABGHgBPGAF4AOiAC0K4tVgAnVBIAsygHy0hAelFjDi6iPFTZC5Wo3bdANiMAjMxas2L9nIQSqrqmjr6RrA+4n62ktJBIc7hugYghkgxltbxgY6hLhHphhDZcQGJBSmukRmE5bmVDsFOYbUlAOblXJAwCMR85CBuqADMAAwqE6gTIAC+eDQMTOhYOFy8-BCC6AHA1hISvACu21rtWhCM-LpgJ-QSYrRaABQ1WgCUANzW89bWCyoVC0QiILQSA7UI5bATwXROZTHHhncGve70T5-XrQODwQbUYajACM01mCwAuvMgA) 

 
 
 #1592
