### ISSUE TITLE
`break-inside: avoid-page` only if the box can fit in the next page?

### ISSUE THREAD

**Issue by FrancoisCapon** [Kozea/WeasyPrint#1634]
Hi!

I think that the break of the second box is more "natural" in this case (the box can't fit in a page).
![test-box-01](https://user-images.githubusercontent.com/46624375/166155809-72329bf1-dd2e-4ce1-b576-16367414e257.png)

In the both case, the box can't fit in a page so is the first break useful?

The algorithm could be:
1. the box can't be placed entirely in the page `n` so place it on the page `n+1`
2.  the box can't be placed entirely in the page `n+1` so leave it on the page `n`

It's just a personal reflection, I really don't know what the specification can said!

**PS** [An example of a PDF generate whith Robots and WeasyPrint](https://github.com/Kozea/WeasyPrint/files/8599358/print.pdf), the content is the MkDocs documention and the template is for an OSCP PEN-200 report. I really appreciate the implementation of: :+1:
```css
margin-break: discard; /* no margin on the top of the page for all elements! */

@top-right {
  /* https://www.w3.org/TR/css-gcpm-3/#string-start */
  /* the current title of level one at the beginning of the toc items of the page */
  content: string(level-1-title, start);
}
```
