### ISSUE TITLE
Include local font file

### ISSUE THREAD

**Issue by ieeemma** [Kozea/WeasyPrint#1708]
Hi! Sorry if this is a stupid question - I've looked at the docs and I cant find a way to use a local font file. I've tried to do this:
```css
@font-face {
    font-family: my-font;
    src: url("file://path/to/font.ttf);
}

html {
    font-family: my-font;
}
```
but this doesn't change the font. What am I doing wrong? Thanks :)
