### ISSUE TITLE
Unable to set table column width on tables td's if a th exists

### ISSUE THREAD

**Issue by stevenlaidlaw** [Kozea/WeasyPrint#172]
If a 'table > thead > tr > th' is set, weasy is not able to set the column widths on td's below it. This is a problem when trying to set widths on table columns where the table header has a colspan greater than 1.

Example:

```HTML
<table>
    <thead> 
        <tr>
            <th colspan="2">The column width will not work in weasy</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Hello</td>
            <td>Clarice</td>
        </tr>
    </tbody>
</table>
```

```CSS
table > tbody > tr > td:first-child {
    width: 20%;
    text-align: left;
}
```
