### ISSUE TITLE
compose Tibetan Buddhist Canon text collection in layout of traditional Pecha tibetan texts

### ISSUE THREAD

**Issue by RimeOCRLIB** [Kozea/WeasyPrint#1785]
Good day.
 
Thank you for all your noble work for benefit of all mankind.
 
At present we need compose Tibetan Buddhist Canon text collection in layout of traditional Pecha tibetan texts. At first stage it is about 350 volumes.

https://www.pechamaker.com/screenshots.html
https://en.wikipedia.org/wiki/Pecha   
 
Does it possible to ask your help to compose this layout and help me understand how adjust hyphenation route for tibetan texts? First of all we need position @left-middle and @right-middle properly and make border around all page content.

```css
@page :left {
  margin: 5mm 35mm 5mm 35mm;
  border: 1px solid black;
  padding:3px;
  @left-middle { display: inline-block; margin-left:-60px; padding:3px; width:200px; height:30px; border:1px solid black; transform: rotate(90deg);  content: "ris" }
  @right-middle {display: inline-block; margin-right:-60px;  padding:3px; width:200px; height:30px; border:1px solid black; transform: rotate(-90deg); content: counter(page); font-variant: small-caps }
}
```
 
![pecha](https://user-images.githubusercontent.com/1236488/209477961-37c51a0e-d1ac-4dac-a816-3c6c106c8cde.gif)
![Screenshot from 2022-12-25 20-24-00](https://user-images.githubusercontent.com/1236488/209477965-23b5367a-5450-4c3f-99da-72690678b077.png)
Of course we will be happy provide Weasyprint contact an every generated PDF (at last few million pages).
 
Open Source Buddhism Library
Stroganov Alexander
