### ISSUE TITLE
Table borders in running header only displayed on first page

### ISSUE THREAD

**Issue by kygoh** [Kozea/WeasyPrint#1882]
The running header of the following html in gist was adapted from [PrintCSS Article on Page Selectors and Page Breaks](https://printcss.net/articles/page-selectors-and-page-breaks):

https://gist.github.com/kygoh/a8b89d8931a6ad0c9dc5fc396e0a2529

The html in the above gist have the following table element:

```html
        <div class="headerCenter">
          <table>
            <tbody>
              <tr>
                <td style="width: 90%;" rowspan="2"><span class="title"></span></td>
                <td style="width: 10%; text-align: center">Page</td>
              </tr>
              <tr>
                <td style="text-align: center"><span class="page-count"></span></td>
              </tr>
            </tbody>
          </table>
        </div>
```

defined as running element for page header from second page onwards:

```css
@top-center{
  content: element(headerCenter);
  width: 100%;
}

.headerCenter{
  position: running(headerCenter);
  font-size:8pt;
}

table {
  width: 100%;
  border-collapse: collapse;
}

td, th {
  border: 1px solid black;
}
```

However, weasyprint renders border only for the second page (first occurrence of running header):

<img width="534" alt="Screenshot 2023-05-20 at 12 53 43 AM" src="https://github.com/Kozea/WeasyPrint/assets/5347201/4e61c4cf-8b49-4198-a43f-0b07d8b16e95">
<img width="533" alt="Screenshot 2023-05-20 at 12 53 53 AM" src="https://github.com/Kozea/WeasyPrint/assets/5347201/b745bcb9-9ede-4a89-81e7-b67b0eb62c21">
<img width="528" alt="Screenshot 2023-05-20 at 12 55 49 AM" src="https://github.com/Kozea/WeasyPrint/assets/5347201/e4583ee7-7bb7-46ae-ba8b-75dba699390a">

Is there anything that can be done to render the border for all pages?
