### ISSUE TITLE
Margin-top only works on First h2 with page-break: left

### ISSUE THREAD

**Issue by Robinaite** [Kozea/WeasyPrint#1979]
Hello, I think I may have stumbled across a bug. 

margin-top on an H2, only works on the first h2, when they have set page-break: left. (Both positive and negative numbers)

Using the following base:

```html
<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>
<p>My first paragraph.</p>

<h2>My First Heading</h2>
<p>My first paragraph.</p>

<h2>My First Heading</h2>
<p>My first paragraph.</p>

<h2>My First Heading</h2>
<p>My first paragraph.</p>

<h1>My First Heading</h1>
<p>My first paragraph.</p>

<h2>My First Heading</h2>
<p>My first paragraph.</p>

<h2>My First Heading</h2>
<p>My first paragraph.</p>

<h2>My First Heading</h2>
<p>My first paragraph.</p>

</body>
</html> 
``` 

With the following Stylesheet:
```css

@page {
    size: 148mm 210mm;
}

@page :left{
    margin-top: 3cm;
}

h1{
    page-break-before: always;
  }

h2 {
    page-break-before: left;
    background-color: red;
    margin-top: -2cm;
    }
``` 

On weasyprint v60.1, by using commandline:
weasyprint -s "E:\Downloads\WeasyPrintBug\stylesheet.css" "E:\Downloads\WeasyPrintBug\page.html" "E:\Downloads\WeasyPrintBug\bug.pdf"

First H2 look:
![Code_07-15-38-18](https://github.com/Kozea/WeasyPrint/assets/6293634/9738be50-7b8d-4f7e-ba11-93be15bdbfbb)

Second H2 Look:
![Code_07-15-38-30](https://github.com/Kozea/WeasyPrint/assets/6293634/c87609d9-7b63-4217-a8ec-e6b4c40027eb)

As you can see, the second heading did not move up.

Expected behaviour:
Second H2 look like First H2.

**Comment by Robinaite** [comment]
I did a bit more digging, and margin-top is only considered on the first h2 after every h1.

**Comment by SystemError7** [comment]
I have the same problem but with the first page, it doesn't apply the ```@page``` nor the ```@page :left``` in the ```html``` like this:
```
      @page {
        size: 210mm 297mm;
        background-color: #808080;

      }
      @page :left {
        margin-top: 1cm;
        margin-left: 1cm;
      }
```
The document was shown the following way:
![image](https://github.com/Kozea/WeasyPrint/assets/146701483/0713748f-0c6e-4d9a-8391-20cba3e9bcf0)
![image](https://github.com/Kozea/WeasyPrint/assets/146701483/334d92f1-785e-4595-9d3c-e5ed7c81baa9)

**Comment by liZe** [comment]
Hi!

That’s actually [required by the specification](https://www.w3.org/TR/css-break-3/#break-margins):

> When an unforced break occurs before or after a block-level box, any margins adjoining the break are truncated to zero.

Until [`break-margin`](https://www.w3.org/TR/css-break-4/#break-margins) is implemented, you can apply a small padding to the body so that margins don’t collapse:

```css
body {
  padding-top: 1px;
  box-decoration-break: clone;
}
```
