### ISSUE TITLE
Incompatible with Tailwind (variables or rgb issues)

### ISSUE THREAD

**Issue by mikerockett** [Kozea/WeasyPrint#1998]
I am trying to render a PDF using a compiled Tailwind stylesheet. The colours do not render as it seems WeasyPrint does not support variables or does not support the rgb syntax being used.

For example:

```css
.border-sunshade-700 {
  --tw-border-opacity: 1;
  border-color: rgb(194 116 0 / var(--tw-border-opacity));
}
```

does not work, but this does:

```css
.border-sunshade-700 {
  border-color: rgb(194, 116, 0);
}
```

I will probably need to find something to restructure the CSS, but it would be nice if WeasyPrint could read this out of the box.
