### ISSUE TITLE
"pages" counter in non-root absolute boxes are broken

### ISSUE THREAD

**Issue by baloersch** [Kozea/WeasyPrint#2029]
Perhaps Bug similar to: https://github.com/Kozea/WeasyPrint/issues/1491

style _**position: absolute;**_ causing incorrect redering...

markup and styles:
my.html

```html
<!DOCTYPE html>
  <head>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <div class="pg">
      <div class="content">
        <div>
          <p>NORMAL CONTENT</p>
          <p>Your Total pages ARE: <span class="totalPages"></span> PAGES</p>
        </div>
      </div>
    </div>
    <div class="pg">
      <div class="content">
        <div class="footer">
          <p>FOOTER </p>
          <p>Your Total pages ARE: <span class="totalPages"></span> PAGES</p>
        </div>
      </div>
    </div>  
  </body>
</html>

``` 

style.css
```css
@page:first {
    size: "A4";
    margin: 2cm 1.6cm 2cm 1.6cm;
    @bottom-right {
        content:"";
    }
}
@page {
    size: "A4";
    margin: 1.6cm 1.6cm 2cm 1.6cm;
    @bottom-right {
        content: counter(page);
    }
}
.pg {
    height: 26cm;
}
.content {
    width: 100%;
    height: inherit;
    position: relative;
}
.footer {
    width: 100%;
    height: 100px;
    position: absolute;
    bottom: 0;
}
span.totalPages:after {
    content: counter(pages);
}

``` 
![bug](https://github.com/Kozea/WeasyPrint/assets/121248244/4a8737c3-9a0a-4592-863a-aa72c2cd73db)
