### ISSUE TITLE
CSS "quotes: none" results in warning

### ISSUE THREAD

**Issue by aleho** [Kozea/WeasyPrint#2111]
A style, e.g. from reset-css, with

```CSS
blockquote, q {
    quotes: none;
}
```

results in the output
> WARNING: Ignored `quotes: none` at 48:3, invalid value.`

According to https://developer.mozilla.org/en-US/docs/Web/CSS/quotes `none` should be a valid value.
