### ISSUE TITLE
Background image flickers

### ISSUE THREAD

**Issue by anuj9196** [Kozea/WeasyPrint#2165]
Using the Statistical Report template with the exact CSS
```css
@page {
    size: A4;
    margin: 1cm;
    
    @top-left {
        background: #fbc847;
        content: counter(page);
        height: 1cm;
        text-align: center;
        width: 1cm;
    }
    
    @top-center {
        background: #fbc847;
        content: '';
        display: block;
        height: .05cm;
        opacity: .5;
        width: 100%ds;
    }
    @top-right {
        {#content: string(heading);#}
        content: element(header);
        font-size: 9pt;
        height: 1cm;
        vertical-align: middle;
        width: 100%;
    }
}

@page :blank {
    @top-left { background: none; content: '' }
    @top-center { content: none }
    @top-right { content: none }
}
@page :first {
    background: url({{ cover_url }}) no-repeat center;
    background-size: cover;
    margin: 0;
}
```

But the background image flickers once and then is hides behind the white background

https://github.com/Kozea/WeasyPrint/assets/6560085/8dcc8f6f-d2eb-4384-bd9d-1e619af8786e
