### ISSUE TITLE
CSS `gap` adds too much space at the end

### ISSUE THREAD

**Issue by Zerotask** [Kozea/WeasyPrint#2167]
Example:
https://play.tailwindcss.com/OM1dOhPIMq

```html
<div class="grid grid-cols-2 gap-4 bg-slate-200">
  <div class="bg-yellow-200">left</div>
  <div class="bg-gray-400">right</div>
  <div class="bg-yellow-200">left</div>
  <div class="bg-gray-400">right</div>
  <div class="bg-yellow-200">left</div>
  <div class="bg-gray-400">right</div>
  <div class="bg-yellow-200">left</div>
  <div class="bg-gray-400">right</div>
  <div class="bg-yellow-200">left</div>
  <div class="bg-gray-400">right</div>
  <div class="bg-yellow-200">left</div>
  <div class="bg-gray-400">right</div>
  <div class="bg-yellow-200">left</div>
  <div class="bg-gray-400">right</div>
</div>
```

```css
.gap-4 {     
    gap: 1rem/* 16px */; 
}
.grid {     
    display: grid; 
}
.grid-cols-2 {     
    grid-template-columns: repeat(2, minmax(0, 1fr)); 
}
```

If I try that with weasyprint (with different colors) I get this result:
![image](https://github.com/Kozea/WeasyPrint/assets/20150243/a7b92c0b-19c8-46d7-b5c2-23dc602d68fc)

I seems to add this. the more divs you have, the greater is the space at the bottom
