### ISSUE TITLE
CSS ` line-height` not working properly

### ISSUE THREAD

**Issue by Zerotask** [Kozea/WeasyPrint#2170]
It seems that [line-height](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height) is adding too much space between elements

Example:
https://play.tailwindcss.com/lbWhMHWdpF

```html
<div class="text-center uppercase">
  <h1 class="text-7xl">This is a main headline</h1>
  <h2 class="text-5xl font-medium">This is a sub-headline</h2>
</div>
``` 

```css
.text-center {
  text-align: center;
}
.uppercase {
  text-transform: uppercase;
}
.text-5xl {
  font-size: 3rem;
  line-height: 1;
}
.text-7xl {
  font-size: 4.5rem;
  line-height: 1;
}
.font-medium {
  font-weight: 500;
}
```

Output on Tailwind Play:
![image](https://github.com/Kozea/WeasyPrint/assets/20150243/8126aeb6-5888-415b-acf9-60bac2719e8b)

Output WeasyPrint:
![image](https://github.com/Kozea/WeasyPrint/assets/20150243/0a73b363-089d-4fd1-8060-12e1bb63512c)

**Comment by liZe** [comment]
Hi!

I tried this sample:
```html
<style>
html {
  font-family: Liberation Serif;
}
.text-center {
  text-align: center;
}
.uppercase {
  text-transform: uppercase;
}
.text-5xl {
  font-size: 3rem;
  line-height: 1;
}
.text-7xl {
  font-size: 4.5rem;
  line-height: 1;
}
.font-medium {
  font-weight: 500;
}
</style>
<div class="text-center uppercase">
  <h1 class="text-7xl">This is a main headline</h1>
  <h2 class="text-5xl font-medium">This is a sub-headline</h2>
</div>
```

Here’s what I get with WeasyPrint:
![Capture d’écran du 2024-06-01 10-37-55](https://github.com/Kozea/WeasyPrint/assets/952243/f649ec2e-4f96-4a05-a40a-9151fa4951a3)

Here’s what I get with a browser:
![Capture d’écran du 2024-06-01 10-38-02](https://github.com/Kozea/WeasyPrint/assets/952243/854d63dd-d6cc-4914-9718-33591316ec07)

If your problem is the space between your h1 and your h2 tags, then it’s probably not the line-height but the margins: h* tags have top and border margins in the default stylesheet, in WeasyPrint and browsers. Looks like there’s a kind of CSS reset stylesheet in `@tailwind base` that removes margins from h* tags, because the margins are back when I remove this line in Tailwind Play.

**Comment by Zerotask** [comment]
Yes, you are right, I meant the space between h1 and h2. Thank you

```css
@layer __play_base__
blockquote, dl, dd, h1, h2, h3, h4, h5, h6, hr, figure, p, pre {
margin: 0;
}
```

must be this style. It seems like I'm already too used to Playwright so I thought it's normal, that headlines have no margin :D
