### ISSUE TITLE
Dynamic page numbers in table of contents

### ISSUE THREAD

**Issue by Dashrath158** [Kozea/WeasyPrint#2189]
Hello folks at weasyprint, I have a flask app that generates dynamic reports using jinjja2 templates and weasyprint library. Is there some way to use the page number functionality of weasyprint to insert dynamic page numbers in my table of contents.  I am not talking about header and footer. Also if you know of other ways to do that feel free to help.

**Comment by grewn0uille** [comment]
Hello,

To generate a table of content, you can use a list of a tags with anchors and in the CSS getting the page number of where the link is pointing to.

For example, in the HTML:
```html
<article id="toc">
  <h2>TOC</h2>

  <ul>
    <li><a href="#part1-title"></a></li>
    <li><a href="#part2-title"></a></li>
  </ul>
</article>
```
and in the CSS:
```css
#toc {
  a::before {
      content: target-text(attr(href)) ' ' leader('.') ' ' target-counter(attr(href), page);
      /* get the title and the related page number */
    }
  }
}
```
