### ISSUE TITLE
position: absolute and top: 0px has no effect

### ISSUE THREAD

**Issue by maluramichael** [Kozea/WeasyPrint#2214]
This is our html preview
<img width="385" alt="image" src="https://github.com/user-attachments/assets/f6170790-1f6d-4dcf-8553-460e1c4f3ef4">
And this is the generated pdf
<img width="338" alt="image" src="https://github.com/user-attachments/assets/7df6b563-37d1-46fe-a625-c73e4a6a21f9">

This would be the related html code
```html
<td class="material-icon text-block-icon-level-0 position-relative">
    <img class="position-absolute" width="18" height="18" src="xxx/chevron_right.svg" alt="">
    <div class="level-placeholder">
    </div>
</td>
```

And here the css
```css
.text-block-element-list .text-blocks .text-block .position-relative {
    position: relative;
}

.text-block-element-list .text-blocks .text-block .material-icon .position-absolute {
    position: absolute;
    top: 0;
}
```

We are using the same css without media queries i guess. Is it possible that position absolute has to be treated differently and is not working or am i doing something wrong?
