### ISSUE TITLE
Images interpolation in PDF/A

### ISSUE THREAD

**Issue by leiserfg** [Kozea/WeasyPrint#2278]
PDF/A can't use interpolation, otherwise, pdf validation tools will complain. I work around this by using 
```css
img {
     /* Default turns on image interpolation, which is not valid in PDF/A-3 */
    image-rendering: pixelated;
}
```
but this should be done automatically as long as `img` uses `image-rendering: auto;`  (and maybe even warn `smooth` is used).
