### ISSUE TITLE
In 63.0 flex layouts are broken - works in 62.3

### ISSUE THREAD

**Issue by EugenMayer** [Kozea/WeasyPrint#2311]
```scss
.dashboard-section {
  display: flex;
  flex-wrap: wrap;
  margin-left: -16px;

  .dashboard-column {
    word-wrap: break-word;
    flex-grow: 0;
    overflow: hidden;
    padding-left: 16px;
  }

  .dashboard-column-1-2 {
    flex-basis: 50%;
    max-width: 50%;
  }
}
```

```html
<div class="dashboard">
  <div class="dashboard-section dashboard-section-widget-2" data-column-structure="1-2_1-2">
    <div class="dashboard-col-1 dashboard-column dashboard-column-1-2">
      <div class="dashboard-column-content"><p>left</p></div>
    </div>
    <div class="dashboard-col-2 dashboard-column dashboard-column-1-2">
      <div class="dashboard-column-content"><p>right</p></div>
    </div>
  </div>
</div>
```

In 63.0 they just overlap
![Image](https://github.com/user-attachments/assets/9470df81-0a83-4b48-96cb-208c46e167a0)

In 62.3 they are side by side
![Image](https://github.com/user-attachments/assets/fa7c60d3-b1bd-4804-b909-e569b93fa8d7)

63.0 generated PDF: [print.pdf](https://github.com/user-attachments/files/17900446/print.pdf)
62.2 generated PDF: [print 62.3.pdf](https://github.com/user-attachments/files/17900459/print.62.3.pdf)
