### ISSUE TITLE
Emojis in `pre` tag add an extra line

### ISSUE THREAD

**Issue by mfontanini** [Kozea/WeasyPrint#2324]
It looks like when you use an emoji inside a `pre` tag this causes a newline to be introduced. The snippets below are similar to what [presenterm](https://github.com/mfontanini/presenterm) generates when exporting a presentation to PDF. Content here is a series of lines of a specific height and a page is capped at a height equal to the line height * number of lines in a page, as if it was a capture of a terminal output (which it is).

In this html, there's a first page with 2 lines without any emoji, then the second page is exactly the same as the first one except with an emoji. You can see in this second page that the second line is no longer the expected one but instead is a newline. The content in page 3 is shifted by one line and an extra page is added because of it. If you remove the emoji in page 2 it all works as expected; similarly if you remove the `pre` tag it also works, but I do want to preserve whitespaces so I need that `white-space: pre`.

I saw a couple of open issues around `white-space: pre-wrap` but I don't know if it's related as there shouldn't be any line wrapping here.

Run using:

```bash
weasyprint -e utf8 -s styles.css input.html output.pdf
```

input.html:

```html
<html>
<body style="color: white">
<!-- page 1 -->
    <div class="content-line"><pre>page 1</pre></div>
    <div class="content-line"><pre>1 / 3</pre></div>
<!-- page 2 -->
    <div class="content-line"><pre>page 2 🎓</pre></div>
    <div class="content-line"><pre>2 / 3</pre></div>
<!-- page 3 -->
    <div class="content-line"><pre>page 3</pre></div>
    <div class="content-line"><pre>3 / 3</pre></div>
</body>
</html>
```

styles.css

```css
pre {
    margin: 0;
    padding: 0;
}

body {
    margin: 0;
    font-size: 10px;
    background-color: #040312;
    width: 248px;
}

.content-line {
    line-height: 12px; 
    margin: 0px;
    width: 248px;
}

@page {
    margin: 0;
    height: 24px;
    width: 248px;
}
```

Output file [bug.pdf](https://github.com/user-attachments/files/18049795/bug.pdf)
