### ISSUE TITLE
Unable to render remote font(s) via @font-face CSS at-rules

### ISSUE THREAD

**Issue by skpaz** [Kozea/WeasyPrint#2335]
We've run into an issue weasyprint v63.1. It seems to have been introduced between 62.3 (no issue) and 63.1 (issue started) - I can reproduce the issue easily. Either that, or the remote style sheet file was updated and introduced a problem with weasyprint. I will endeavor to see if I can determine when/if the remote style sheet was changed, if at all.

The style sheet is remote and contains CSS at-rules.

```txt
INFO: __init__.py:162 (__init__): Step 1 - Fetching and parsing HTML - cover.html
INFO: __init__.py:289 (__init__): Step 2 - Fetching and parsing CSS - https://example.com/web/fonts/inter.css
INFO: __init__.py:289 (__init__): Step 2 - Fetching and parsing CSS - CSS string
WARNING: __init__.py:188 (validation_error): Ignored `text-shadow: 2px 2px 3px rgba(0,0,0,0.5),4px 4px 5px rgba(255,255,255,0.5),` at 20:7, unknown property.
INFO: __init__.py:69 (__init__): Step 3 - Applying CSS
INFO: document.py:242 (_build_layout_context): Step 4 - Creating formatting structure
INFO: page.py:907 (make_all_pages): Step 5 - Creating layout - Page 1
INFO: __init__.py:118 (generate_pdf): Step 6 - Creating PDF
INFO: __init__.py:228 (generate_pdf): Step 7 - Adding PDF metadata
```

Here is the content of the style sheet:

```css
/* inter-regular - latin */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('/web/fonts/inter/inter-v3-latin-regular.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('/web/fonts/inter/inter-v3-latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('/web/fonts/inter/inter-v3-latin-regular.woff2') format('woff2'), /* Super Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-regular.woff') format('woff'), /* Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-regular.ttf') format('truetype'), /* Safari, Android, iOS */
       url('/web/fonts/inter/inter-v3-latin-regular.svg#Inter') format('svg'); /* Legacy iOS */
}

/* inter-500 - latin */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: url('/web/fonts/inter/inter-v3-latin-500.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('/web/fonts/inter/inter-v3-latin-500.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('/web/fonts/inter/inter-v3-latin-500.woff2') format('woff2'), /* Super Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-500.woff') format('woff'), /* Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-500.ttf') format('truetype'), /* Safari, Android, iOS */
       url('/web/fonts/inter/inter-v3-latin-500.svg#Inter') format('svg'); /* Legacy iOS */
}

/* inter-600 - latin */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url('/web/fonts/inter/inter-v3-latin-600.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('/web/fonts/inter/inter-v3-latin-600.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('/web/fonts/inter/inter-v3-latin-600.woff2') format('woff2'), /* Super Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-600.woff') format('woff'), /* Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-600.ttf') format('truetype'), /* Safari, Android, iOS */
       url('/web/fonts/inter/inter-v3-latin-600.svg#Inter') format('svg'); /* Legacy iOS */
}

/* inter-700 - latin */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url('/web/fonts/inter/inter-v3-latin-700.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('/web/fonts/inter/inter-v3-latin-700.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('/web/fonts/inter/inter-v3-latin-700.woff2') format('woff2'), /* Super Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-700.woff') format('woff'), /* Modern Browsers */
       url('/web/fonts/inter/inter-v3-latin-700.ttf') format('truetype'), /* Safari, Android, iOS */
       url('/web/fonts/inter/inter-v3-latin-700.svg#Inter') format('svg'); /* Legacy iOS */
}
```

Another, local style sheet calls `html, body {font-family: inter, sans-serif;}`, but it fails to use the designated font and instead defaults to a local sans-serif font. In this case it's Verdana. I can also reproduce the issue by trying to call the at-rule font directly via `style`.

```txt
% pdffonts cover.pdf 
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
IETZIE+Verdana-Bold                  CID TrueType      Identity-H       yes yes yes     15  0
VMAKMM+Verdana-Bold-Italic           CID TrueType      Identity-H       yes yes yes     19  0
```

On my local machine it defaults to Verdana, but in our build pipelines on Ubuntu it uses DejaVu Math TeX Gyre for some insane reason ... obviously not a sans-serif font.
