### ISSUE TITLE
After #2026 the rest of flex container is discarded if it doesn't fit on page

### ISSUE THREAD

**Issue by mbystryantsev** [Kozea/WeasyPrint#2346]
After fix #2026 (bc971312ac847d2b7d62de5d8e0189f1fe435c9b) , remaining part of flex container is discarded if it does not fit on the page.

The following example is rendered only until the end of the first page.

```css
.wrapper {
  display: flex;
  flex-direction: column;
}

.spacer {
  width: 100vw;
  padding-bottom: 250px;
}

@page {
  size: A4;
  margin: 5mm 0 5mm 3mm;
  padding: 0 5mm 0 5mm;
}

@media print {
  html, body {
    width: 195mm;
    height: 297mm;
  }
}
```

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Test</title>
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <div class="wrapper">
      <div>
        <div class="spacer">1. Spacer</div>
        <div class="spacer">2. Spacer</div>
        <div class="spacer">3. Spacer</div>
        <div class="spacer">4. Spacer</div>
        <div class="spacer">5. Spacer</div>
        <div class="spacer">6. Spacer</div>
      </div>    
      <div>
        THIS CONTENT MUST BE DISPLAYED
      </div>
    </div>
  </body>
</html>
```
