### ISSUE TITLE
Facing difficulties with the flexbox

### ISSUE THREAD

**Issue by harkishankhuva** [Kozea/WeasyPrint#2351]
Hello, so I'm trying to create a PDF from HTML that has flexbox in it, below is the code for the stylesheet and the HTML file

Stylesheet:
```css
body {
    height: 100%;
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-direction: column;
}
@page{
    size: "A4";
}
```

HTML
```html
<html>
  <head>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <div class="head_text">
      <p>
        Head text
      </p>
    </div>
    <div class="bottom_text">
      <p>
        bottom text
      </p>
    </div>
  </body>
</html>
```

This is the image what I see in the browser:
![Image](https://github.com/user-attachments/assets/e66eae4c-9e7f-4ed4-81c4-7d665e5520ca)

But in the PDF it becomes like this:
![Image](https://github.com/user-attachments/assets/89bb12bd-eaa3-4625-8519-a1835184bd47)

Since I didn't find any working solution other than generating the PDF with the headless browser, my last hope is using the weasyprint.
