### ISSUE TITLE
Default font is rendering even with CSS

### ISSUE THREAD

**Issue by O-Schell** [Kozea/WeasyPrint#2366]
Weasyprint seems to not render fonts related to the body and fallback to the default font *(btw, big japanese vibes here!)*. I've scoured the Internet but find nothing like what I experience... Can it have a link with the fact that I **can't** install/launch anything with an exe (but I can use pip without problems) ?

Note: 
- The following warning appears in my prompt, without affecting the generation of the PDF but everything I tried never made him change or disappear...
```log
Fontconfig error: Cannot load default config file: No such file: (null)
```
 - text inside the em tags seems to no be affected by this bug.

![Image](https://github.com/user-attachments/assets/089551a8-8394-4b7b-b392-16ff46f7a032)

```python
    GTK_FOLDER = r"...\_somewhere_on_my_pc\...\GTK3\gtk-nsis-pack\bin"
    os.add_dll_directory(GTK_FOLDER)
    from weasyprint import HTML, CSS
    from weasyprint.text.fonts import FontConfiguration
    font_config = FontConfiguration()

    html_content="..." #contain HTML 
    with tempfile.NamedTemporaryFile(
        delete=False,
        suffix=".html",
    ) as tmp_html:
        tmp_html.write(html_content.encode("ascii", "xmlcharrefreplace"))
        tmp_html_path = tmp_html.name

    output_pdf_path = "Data/Temp/output.pdf"
    output_css_path = (
        "...\_somewhere_on_my_pc\main.css"
    )

    HTML(tmp_html_path).write_pdf(
        output_pdf_path,
        stylesheets=[CSS(output_css_path, font_config=font_config)],
        font_config=font_config,
    )
    print("PDF conversion successful!")
    return documentation
```

HTML:
```html
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sample Documentation</title>
        <link rel="stylesheet" href="styles.css">
    </head>
    <body>
        <h1 id="sample-documentation">Sample Documentation</h1>
        <div class="toc">
            <ul>
                <li><a href="#introduction">Introduction</a></li>
                <li><a href="#features">Features</a>
                    <ul>
                        <li><a href="#feature-1">Feature 1</a></li>
                        <li><a href="#feature-2">Feature 2</a></li>
                    </ul>
                </li>
                <li><a href="#examples">Examples</a></li>
            </ul>
        </div>

        <h2 id="introduction">Introduction</h2>
        <p>This is a sample documentation to demonstrate the structure and styling of a typical documentation page. It includes special characters like é, ç, and @ to ensure proper encoding.</p>

        <h2 id="features">Features</h2>
        <h3 id="feature-1">Feature 1</h3>
        <p><em>DEFINITION</em>: This is the definition of Feature 1. It includes special characters like é and ç.</p>
        <p><em>SYNTAX</em>: <em>Emphasis on something</em></p>
        <pre><code>FEATURE1 / OPTION1
    FEATURE1 / OPTION2
    FEATURE1 / ÉXAMPLE@OPTION
    </code></pre>
        <p><em>EXAMPLES</em>: <em>no examples</em></p>

        <h3 id="feature-2">Feature 2</h3>
        <p><em>DEFINITION</em>: This is the definition of Feature 2. It includes special characters like @ and ç.</p>
        <p><em>SYNTAX</em>:</p>
        <pre><code>FEATURE2 / OPTION1
    FEATURE2 / OPTION2
    FEATURE2 / @EXAMPLEÇOPTION
    </code></pre>
        <p><em>EXAMPLES</em>: <em>no examples</em></p>

        <h2 id="examples">Examples</h2>
        <p>Here are some examples of how to use the features:</p>
        <pre><code>EXAMPLE1 / OPTION1
    EXAMPLE2 / OPTION2
    EXAMPLE3 / ÉXAMPLE@ÇOPTION
    </code></pre>
    </body>
    </html>
```
CSS:
```css
@font-face {
    font-family: 'Aptos';
    src: url('./GUI/fonts/Aptos/Aptos-Mono.ttf') format('ttf');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'Montserrat';
    src: url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');
    font-weight: 400;
    font-style: normal;
}


@font-face {
    font-family: 'DM Mono';
    src: url('https://fonts.googleapis.com/css2?family=DM+Mono&display=swap');
    font-weight: 400;
    font-style: normal;
}




/* Apply the Colibri font to the body and headings */
body, h1, h2, h3, h4 {
    font-family: 'Aptos', monospace;
    margin: 0;
    padding: 0;
}

/* Style for the body */
body {
    font-weight: 400;
    font-style: normal;
    font-size: 1em;
    color: #1A1A1A;
    background-color: white;
    padding: 20px;
}

p {
    font-weight: 400;
    font-style: normal;
    font-size: 1em;
    color: #1A1A1A;
    background-color: white;
    padding: 20px;
}

p body {
    font-weight: 400;
    font-style: normal;
    font-size: 1em;
    color: #1A1A1A;
    background-color: white;
    padding: 20px;
}

/* Style for h1 */
h1 {
    font-family: 'Montserrat';
    font-size: 3em;
    color: #101010;
    margin-bottom: 20px;
}

/* Style for h2 */
h2 {
    font-family: 'Montserrat';
    font-size: 2.5em;
    color: #101010;
    margin-bottom: 15px;
}

/* Style for h3 */
h3 {
    font-family: 'Montserrat';
    font-size: 2em;
    color: #101010;
    margin-bottom: 10px;
}

/* Style for the table of contents */
.toc {
    font-family: 'DM Mono';
}

/* Style for code blocks */
code {
    font-family: 'DM Mono';
    background-color: #F1F1F1;
    padding: 5px;
    border-radius: 4px;
    color: #999;
    display: block;
    margin: 10px 0;
}

/* Ensure pre and code blocks within pre are styled correctly */
pre {
    font-family: 'DM Mono';
    background-color: #F1F1F1;
    padding: 5px;
    border-radius: 4px;
    color: #999;
    margin: 10px 0;
    white-space: pre-wrap;
}

pre code {
    font-family: 'DM Mono';
    background-color: #F1F1F1;
    padding: 5px;
    border-radius: 4px;
    color: #999;
    display: block;
    margin: 10px 0;
}

```

**Comment by liZe** [comment]
Hi!

It looks like your Aptos font is not found, and it fallbacks to the monospace font as declared here:

```css
body, h1, h2, h3, h4 {
    font-family: 'Aptos', monospace;
    […]
}
```

Could you try replacing Aptos’ `src` line in `@font-face` by another Google font and see if it works? If it does, it means that for some reason (probably the relative link) your `Aptos-Mono.ttf` font is not found.
