### ISSUE TITLE
":host" should not break remaining css selectors

### ISSUE THREAD

**Issue by doits** [Kozea/WeasyPrint#2373]
The following css works:

```css
:root {
  --some-variable: #f00;
}
```

But once a `:host` is added it breaks:

```css
:root, :host {
  --some-variable: #f00;
}
```

> WARNING: Invalid or unsupported selector, ':root,:host'

`--some-variable` is not available anymore.

Same goes for selectors like `html, :host` etc..

I think it should simply ignore `:host` (which has no meaning here because there is no shadow dom afaik) but apply the remaining ones (`:root` and `html` in my example).
