### ISSUE TITLE
Input elements not printing

### ISSUE THREAD

**Issue by Schille** [Kozea/WeasyPrint#328]
Am I doing something wrong or is the visual output of `input` elements not supported?
I have a minimal HTML document with just one input (and no CSS) like so:
`[...]`
`<input type="text" value="Foo">`
`[...]`
Unfortunately, the output is blank. Same thing for `type="radio"` and so on.
I couldn't find any documentation about this, so I will be glad if anybody can give me a hint.

**Comment by liZe** [comment]
There's a bug open (#61) to support form fields in PDF files.

If you only want to draw input tags, you just have to add some CSS as you do for other tags. There's no default CSS in WeasyPrint, that's why they are not drawn (just as an empty `div` or `span` would be).

```html
<style>input:before{content:attr(value)}</style>
<input style="background: red" type="text" value="Foo">
```

**Comment by JacoboCarbo** [comment]
From my experience, the the best way to do this is by using:

`<textarea type="text" rows="2">`

The textarea tag does get rendered by weasyprint.

**Comment by obonyojimmy** [comment]
Here a simple solution for checkbox input : 

```
input[type="checkbox"] {
  height: 1em;
  width: 1em;
  display: inline-block;
  border: black 2px solid;
  margin: 0 0.5em;
}
```

**Comment by notanumber** [comment]
Is this documented somewhere? I just spend several days banging my head against the wall trying to debug my document output, unable to figure out why the form values weren't being displayed. I thought I was going crazy.

**Comment by liZe** [comment]
> Is this documented somewhere? I just spend several days banging my head against the wall trying to debug my document output, unable to figure out why the form values weren't being displayed. I thought I was going crazy.

It's not documented yet, and I'm sorry for that.

I should add a stylesheet somewhere in the documentation to explain how to render forms in WeasyPrint.

**Comment by liZe** [comment]
@notanumber You'll now find a sample [in the documentation](https://weasyprint.readthedocs.io/en/latest/tips-tricks.html#display-forms), I hope that it will be useful for everybody!

**Comment by notanumber** [comment]
@liZe thanks for the update, and apologies if my comment sounded rude. This library is great and much easier to work with then any other Python based HTML to PDF library I've tried in the past!

**Comment by robertpro** [comment]
> Here a simple solution for checkbox input :
>
> input[type="checkbox"] {
>   height: 1em;
>   width: 1em;
>   display: inline-block;
>   border: black 2px solid;
>   margin: 0 0.5em;
> }

This is partially working for me, were you able to display `checked` checkboxes?

**Comment by liZe** [comment]
> This is partially working for me, were you able to display `checked` checkboxes?

You can for example use a different background for checked checkboxes:

```css
input[checked] { background: red }
```

**Comment by matiasrebori** [comment]
I had this problem and this is my solution if its useful for someone, i copy some css and modified a little to work with weasyprint.

![Screenshot 2022-03-29 130404](https://user-images.githubusercontent.com/51835176/160680291-e867636f-501f-48ad-b8ac-7144a4228c3e.png)
### CSS
```css       
/* css para los checkbox */
.checkbox label:after {
    content: '';
    display: table;
    clear: both;
}

.checkbox .cr {
    position: relative;
    display: inline-block;
    border: 1px solid #a9a9a9;
    border-radius: .25em;
    width: 1.3em;
    height: 1.3em;
    float: left;
    margin-right: .5em;
}

.checkbox .cr .cr-icon {
    position: absolute;
    font-size: .8em;
    line-height: 0;
    top: 50%;
    left: 15%;
}

.checkbox label input[type="checkbox"] {
    display: none;
}

/* no mostrar check  */
.checkbox label input[type="checkbox"] + .cr > .cr-icon {
    opacity: 0;
}

/* mostrar check cuando tenga atributo checked */
.checkbox label input[type="checkbox"]:checked + .cr > .cr-icon {
    opacity: 1;
}

/* bajar opacidad del check cuando este disabled */
.checkbox label input[type="checkbox"]:disabled + .cr {
    opacity: .5;
}

/* etiqueta label con clase checkbox */
label.checkbox {
    width: 100%;
}

/* etiqueta span (para texto) con clase checkbox */
span.checkbox {
    font-size: 0.8rem;
    font-weight: 400;
    color: #212529;
}
``` 
### HTML

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<div class="checkbox">
    <label class="checkbox">
            <input type="checkbox" value="">
        <!-- icon -->
        <span class="cr"><i class="cr-icon fas fa-check"></i></span>
        <!-- text -->
        <span class="checkbox"> option one </span>
    </label>
</div>
<div class="checkbox">
    <label class="checkbox">
            <input type="checkbox" value="" checked>
        <!-- icon -->
        <span class="cr"><i class="cr-icon fas fa-check"></i></span>
        <!-- text -->
        <span class="checkbox"> option two is checked by default</span>
    </label>
</div>
<div class="checkbox">
    <label class="checkbox">
            <input type="checkbox" value="" checked disabled>
        <!-- icon -->
        <span class="cr"><i class="cr-icon fas fa-check"></i></span>
        <!-- text -->
        <span class="checkbox"> option three is disabled </span>
    </label>
</div>
````
