### ISSUE TITLE
Unexpected SVG crop

### ISSUE THREAD

**Issue by mofr** [Kozea/WeasyPrint#339]
Weasyprint 0.30 scales down svg image and crops it.
Source html:
```html
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <img src="naturelogofinal.svg" class="fit"/>
    <img src="naturelogofinal.png" class="fit"/>
</body>
</html>
```

style.css:
```css
@page {
    size: A4 portrait;
    margin: 1cm;
}

img.fit {
    width: 100%;
    border: 1px solid black;
}
```

However same picture in png format works fine.
First image is SVG and the second one is PNG:
![image](https://cloud.githubusercontent.com/assets/1718475/17275942/98442b16-5743-11e6-99a4-884f484edcd2.png)

PNG and SVG images used:
[naturelogofinal.zip](https://github.com/Kozea/WeasyPrint/files/392352/naturelogofinal.zip)
