### ISSUE TITLE
content() function captures text after text-transform

### ISSUE THREAD

**Issue by mdekstrand** [Kozea/WeasyPrint#343]
With the following effective rule:

```css
h1 {
    text-transform: uppercase;
    -weasy-string-set: section content();
}
```

Weasyprint sets the `section` register/variable to the uppercased version of the `<h1>`'s content, instead of the original lowercase version.

I am not entirely sure if I am right about the expected behavior, but the CSS Text Transformation spec says this about [`text-transform`](https://www.w3.org/TR/css-text-3/#text-transform):

> This property transforms text for styling purposes. (It has no effect on the underlying content.)

This suggests to me that `content()` should return the untransformed text. The [definition of `content()`](https://www.w3.org/TR/css-content-3/#content-function) does not shed light on this matter.
