### ISSUE TITLE
Find a way to easily reach the internal values of the rendered tree

### ISSUE THREAD

**Issue by G-E-N-E** [Kozea/WeasyPrint#434]
I'm not sure if this is a bug or intended behavior but the height of a box is 'auto' after rendering unlike the width of the box which appears to be being calculated based on the content.

How can I get the calculated height of the element id=header from the rendered document, i.e. 
doc = HTML(string=html_below).render(stylesheet=[CSS(css_below)])?

It seems like the width of the elements is calculated but the height remains set to 'auto'.
I'd like to resolve this to a unit so unfixed elements (not shown) can be positions relative to the dynamic height.

# HTML

```html
<div id="header">
  <div id="header-right">
    <div>Row 1, Column 2</div>
    <div>Row 2, Column 2</div>
  </div>

  <div>
    <div>Row 1, Column 1</div>
    <div>Row 2, Column 1</div>
  </div>
</div>
```

# CSS

```css
#header {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
}

#header-right {
  float: right;
  text-align: right;
}
```
