### ISSUE TITLE
No Support for Japanese (non-ascii characters)

### ISSUE THREAD

**Issue by gauravt1** [Kozea/WeasyPrint#435]
It works normally for English characters but shows boxes in case of non-ascii characters. It raises to me a warning that "@font-face support needs Pango >= 1.38". I try to upgrade it from repo but It has many dependencies associated. Is there any workaround to fix it?

**Comment by liZe** [comment]
Thank you for reporting your problem.

> Is there any workaround to fix it?

Yes. You have to install the needed font on your system and use this font in the CSS instead of the one used with @font-face.

**Comment by liZe** [comment]
@gauravt1 Did you manage to solve your problem?

**Comment by gauravt1** [comment]
I'm still struggling with the issue. It works fine on Ubuntu - 16.04 without installing specific font. But when I deployed it to system with Ubuntu - 14.04, the Django server raises a warning - "WARNING: @font-face support needs Pango >= 1.38". May be I'm interpreting it incorrectly, but it is happening.

I try to install "Pango - 1.38" manually but didn't find any specific one. It's repository exists but it has lots of hidden dependencies.

I can share my code snippet as well if you need it. Please let me know if you have any questions. Thanks for your help :)

**Comment by liZe** [comment]
You need:
- to install a font that has the Japanese characters,
- to add some CSS to override the @font-face CSS that is not supported.

For example, you have a font called "Japanese Font" installed on your system. Your document has some code like this:
```css
@font-face {
  font-family: 'MyWebFont';
  src: url('webfont.otf');
}

body {
  font-family: 'MyWebFont', sans-serif;
}
```

You have add a stylesheet with:
```css
body {
  font-family: 'Japanese Font';
}
```

That's all!
