### ISSUE TITLE
Named strings: "start" does not work?

### ISSUE THREAD

**Issue by netzaffin** [Kozea/WeasyPrint#465]
As it seems, the param "start" does not work at the moment.
```css
@page:left {
   @top-left { content: string(chapter, start); }
   /*@top-left { content: string(chapter, first); }*/ /*has same result*/

}

h2 { -weasy-string-set: chapter content(); }
```

Can anyone confirm this issue with the latest v0.36?
If there is a h2 tag on the current page (not at the beginning), the new chapter will be used.

Is there any way to avoid this?
