### ISSUE TITLE
-weasy-string-set does not work with display: none

### ISSUE THREAD

**Issue by jmidgren** [Kozea/WeasyPrint#473]
When using -weasy-string-set with content that is hidden using css "display: none;" the content is not copied to the css string.

Example:
```html
...
<div id="myvalue">This is the text</div>
...
```

```css
@page {
  @top-center {
    content: string(myvalue);
  }
}

#myvalue {
  display: none;
  -weasy-string-set: myvalue content();
}
```

Here I expect the div not to show but "This is the text" to appear in the page header. Instead the text is hidden both in the body div and the header.

If I remove the "display: hidden;" directive from my style sheet, the text appears both in the document body and header.

I'm not 100% sure this is an error (the feature is after all only from a draft specification), but it seems reasonable that it should be possible to copy hidden text into CSS strings.

**Comment by jmidgren** [comment]
A workaround is to avoid "display: none" and instead use e.g. "font-size: 0pt;" but that may have other implications on how style is applied to your document.

**Comment by liZe** [comment]
> I'm not 100% sure this is an error (the feature is after all only from a draft specification)

It's only [a draft](https://www.w3.org/TR/css-gcpm-3/#setting-named-strings-the-string-set-pro), but it's explicit:

> The content values of named strings are assigned at the point when the content box of the element is first created (or would have been created if the element’s display value is none).

It's a bug!

**Comment by Tontyna** [comment]
Workaround for named strings from META elements:

```css
head, 
head > title, 
head > meta {display:inline}

meta[author] { string-set: author attr(author); }
head > title { string-set: title content(); }   
```

**Comment by eligiobz** [comment]
Sorry to bother, but you could give me an example how would this look on a Jinja2 template? I’m using them to generate the PDFs.

Cheers.

**Comment by Tontyna** [comment]
Don't know Jinja2, but I'm shure there's a place to tell the template engine which css styles to apply. Something like `<style>...</style>` or `<link rel="stylesheet" ...>` in html. Or maybe there's an *include*-statement for stylesheets? The same location where -- I suppose -- you already tell WeasyPrint what e.g. `@page` style to use.

**Comment by larrykollar** [comment]
If I have a standard `<meta>` tag like this:

```html
<meta name="author" content="Joe Bloggs"/>
```

Then I would expect (according to Tontyna's workaround) this would work:

```css
head > meta { display: inline; }
meta[name="author"] { string-set: author attr(content); }
```

It's not working in Weasyprint, but does work in another formatter I've tried (Oxygen PDF Chemistry). Am I missing something?

Maybe the fix is to change the UA stylesheet; since `<meta>` carries its content in attributes and is otherwise empty.
