### ISSUE TITLE
Does WeasyPrint support @page content flow()

### ISSUE THREAD

**Issue by yejialin** [Kozea/WeasyPrint#554]
i need set multi-line headers  in my table-pdf like 
Line 1 --- the title
Line 2 --- the datetime
i found a way to solve this problem is using flow() in @page in every page content,
```
@page {
    margin-top: 100px;
    @top {
        content: flow(header);  
        border-bottom: solid red
    }
}
```
but i try this and it looks like flow() can not parse in weasyprint

thanks a lot

**Comment by liZe** [comment]
I'm not sure to understand exactly what you want, but you can insert multi-line content in headers with an escaped line-feed character and a white-space attribute to keep it:

```css
@page {
    @top-center {
        content: 'title\00000adatetime';
        white-space: pre-line;
    }
}
```

Where did you find the `flow` hack, I can't find it in specs or even on MDN?
