### ISSUE TITLE
Unwanted margin in multi-page table

### ISSUE THREAD

**Issue by morloy** [Kozea/WeasyPrint#583]
We discovered a very strange margin issue in a table that spans over two pages.
As you can see in the image, one single number has a margin to the right. The HTML code for all rows is exactly the same. So I'm a bit confused about how to trace this bug. Maybe some of the experts can give a hint? 
![image](https://user-images.githubusercontent.com/7600303/37031084-c562b87c-213d-11e8-8c64-7ed7ca7279fa.png)

Here's the source HTML and the produced PDF from WeasyPrint.
[report.zip](https://github.com/Kozea/WeasyPrint/files/1784844/report.zip)

**Comment by Tontyna** [comment]
Can reproduce the error and it's - - - STRANGE!
There seem to be magic numbers involved. Don't get it. Yet.

Stupid workaround at the moment: 
Alter your `@page`'s top margin. Either reduce it to 2.8cm or less. Or increase it to 3.2cm or more.

```css
/* report.html, line 12433 ff */
    @page {
      size: A4;
      margin: 3cm 2cm; 
      /* margin-top between 2.9 and 3.1 produces the strange error */
      margin-top: 2.8cm;
      @bottom-right {
        font-family: 'Montserrat';
        content: "Page " counter(page) " of " counter(pages);
      }
    }
```

As I said: strange magic numbers. I keep at it and will report my findings.
