### ISSUE TITLE
Loop/crash on umlaut

### ISSUE THREAD

**Issue by jsonn** [Kozea/WeasyPrint#585]
Processing the HTML from [test.zip](https://github.com/Kozea/WeasyPrint/files/1793482/test.zip) will result in an infinite loop with 0.42 and `TypeError: 'NoneType' object is not subscriptable` with 0.42.2.

**Comment by Tontyna** [comment]
Insert a `<meta charset="utf-8" />` and your ö will be ok.

Concerning your CSS, it looks like WeasyPrint tries to satisfy all your demands and finally gives up. 
If I was to decide where to position the absolutely positioned elements -- I'd give up, too:

```css
#datum {
  position: absolute;
  top: 12cm; 
  bottom: 16.5cm;
  left: 15.3cm;
  right: 2cm;
  margin: 0;
}
```

Don't specify values for more than 2 adjacent corners (top/left or top/right etc.) and WeayPrint doesn't crash anymore.

Nevertheless, WeasyPrint shouldn't crash, it should gracefully ignore disastrous commands.
