### ISSUE TITLE
Is there an example to generate pdf with header and footer for every page? 

### ISSUE THREAD

**Issue by khasburrahman** [Kozea/WeasyPrint#693]
Is there an example to generate pdf with header and footer for every page?
I tried using table head and table footer to create the header and footer
but it seems not yet supported as #36

```
<table>
  <thead>
     <tr>
        <th>
           header header header </br>
           header header header </br>
        </th>
     </tr>
  </thead>


  <tbody>
     <tr>
        <td>
              content content content </br>
              ... long content ...
              content content content </br>
        </td>
     </tr>
  </tbody>


  <tfoot>
     <tr>
        <td>
            footer footer footer </br>
            footer footer footer </br>
        </td>
     </tr>
  </tfoot>
</table>
```

then I came up with style `position:fixed` css attribute

```
<div style="position:fixed; top: 1cm; left: 1cm;">
  header header header </br>
  header header header </br>
</div>
<div style="margin-top: 2cm;" >
  content content content </br>
  ...long content...
  content content content </br>
</div>
<div style="position:fixed; bottom: 1cm; left: 1cm;" >
  footer footer footer </br>
  footer footer footer </br>
</div>
```
it works but the content is overlapping with the header / footer
`margin-top` is only works on the first page.
any idea / example for this problem ? Thanks

**Comment by ramonski** [comment]
Hi @khasburrahman,

you probably need to define the margins in the [@page](https://developer.mozilla.org/en-US/docs/Web/CSS/@page) descriptor:

```css
@page {
  /* width/height according to the format */
  size: 210.0mm 297.0mm;

  /* margins on every page */
  margin-top: 10.0mm;
  margin-right: 20.0mm;
  margin-bottom: 20.0mm;
  margin-left: 20.0mm;
}
```

another solution if your footer contains only a single text line could be this:

```css
@page {
  @bottom-center {
    content: 'Here comes a simple footer text';
  }
  @bottom-right {
    content: "Page " counter(page) " of " counter(pages);
  }
}
```

The final solution would be however to have running CSS headers/footers, which is not supported (yet?) by WeasyPrint, see https://github.com/Kozea/WeasyPrint/issues/598

But this would be actually a thing I'm also highly interested in;)
