### ISSUE TITLE
Support for CSS Overflow 4 module

### ISSUE THREAD

**Issue by TUSF** [Kozea/WeasyPrint#787]
This is not an immediate feature request; the draft for the Overflow 4 spec is not even complete. This issue is to track and bring awareness to this feature for implementing in the future, if (or when) the draft is more developed.

https://drafts.csswg.org/css-overflow-4/

My main interest in this particular module, is the capacity to have a kind of pseudo line-selector, which is sorely lacking in the current spec, and is unlikely to actually be added. According to the current draft, this could be achieved using something like the following:

```CSS
  /* Latin often had text that reversed direction each line. */
p:lang(la) {
  max-lines: 1;
  continue: fragments;
}
p:lang(la)::nth-fragment(even) {
  transform: scale(-1, 1);
}
```

This'll also be pretty neat for more complex column layouts without needing to make a new element (see [Example 9](https://drafts.csswg.org/css-overflow-4/#example-11848354) for example.)
