### ISSUE TITLE
front-matter main-matter page numbering

### ISSUE THREAD

**Issue by pmjdebruijn** [Kozea/WeasyPrint#904]
I'm trying to create a document with a proper title page front-matter and back-matter, with properly restarting page numbering.

If I enable counter-reset: page on the page elements, with a proper encapsulating div for both front-matter and back-matter, the counter-reset is executed on every page:

[matter_2.pdf](https://github.com/Kozea/WeasyPrint/files/3411382/matter_2.pdf)
[matter_2.txt](https://github.com/Kozea/WeasyPrint/files/3411383/matter_2.txt)

When I kludge it, with a separate empty div, I get a unwanted empty page, but the number resetting works fine:

[matter_1.pdf](https://github.com/Kozea/WeasyPrint/files/3411380/matter_1.pdf)
[matter_1.txt](https://github.com/Kozea/WeasyPrint/files/3411381/matter_1.txt)

The other idea that came to mind is using the :first selector with my named pages, but...
@page front :first { counter-reset: page 1; }
seems to be ignored, and
@page:first front { counter-reset: page 1; }
results in the following error:
WARNING: Unsupported @page selector ":first front
", the whole @page rule was ignored at 11:1.

I'd love to hear your thoughts on this issue...

**Comment by pmjdebruijn** [comment]
Presumably this may be related:
https://github.com/Kozea/WeasyPrint/commit/dffab39c3718c579e0facdfbdd652d8187ae0fc1

**Comment by pmjdebruijn** [comment]
And https://github.com/Kozea/WeasyPrint/issues/562

**Comment by pmjdebruijn** [comment]
@page main:left { counter-reset: page 10; }

seems to work fine.

**Comment by Tontyna** [comment]
> @page main:left { counter-reset: page 10; }
> seems to work fine.

Huh? This rule results in main pages which are numbered 10, 11, 10, 11, ...

Unless the pseudo-selector `:first` is supported for named pages there's almost no chance to get what you want with the builtin `page` counter. (Dunno why the [spec](https://drafts.csswg.org/css-page-3/#valdef-page-first) restricts this useful selector: "The :first pseudo-class matches the **first printed page** of a document")

Can be achieved by using your own `main-pagecounter`:

```css
@page main
{
  counter-increment: main-pagecounter;
  @bottom-center
  {
    font-family: Arimo, Arial, Helvetica, sans-serif;
    content: counter(main-pagecounter);
  }
}

article#contents a::after
{
  content: target-counter(attr(href), main-pagecounter);
  float: right;
}
```
