### ISSUE TITLE
Deployment Package/Layer for AWS Lambda

### ISSUE THREAD

**Issue by mojimi** [Kozea/WeasyPrint#916]
The intent of this issue is to bring a community effort to get a documented way to get WeasyPrint working on an AWS Lambda environment.

There has been other issues and solutions related to this before but none were conclusive or adaptable

Key points :

1. Users should be able to build the package themselves, choosing a weasyprint/python version combination (Only 3.6 and 3.7 are supported by Lambda)
2. The main tool should be to use a docker with the lambci/lambda image, it mimicks aws lambda very closely, then install the packages and extract them
3. Another issue is the file system in lambda, you only have access to the /tmp/ folder so libraries that need to be in a specific location need to be rethinked or find out if they're looking for a environment variable we can edit

Hopefully we can finally get this issue sorted, generating a PDF in AWS Lambda is a common scenario and it allow for a very cheap and fast hosting/deployment structure.

Also, once sorted out we can share with the community the ARN of a WeasyPrint Lambda Layer that anyone can use (sharing a lambda layer is free and incurs no additional charges)

**Comment by mojimi** [comment]
I'll share what I have so far :

I'm trying to get a base idea using serverless-framework with serverless-python-requirements plugin, it automatically sets up a docker resembling aws lambda, then installs and packages all python packages from a requirements.txt

It also allows for extra packages to be included, for example I tried the following configuration setup, since installing just weasyprint makes it output `cannot load library 'pango-1.0'` :

```docker
FROM lambci/lambda:build-python3.7

# Install your dependencies
RUN yum -y install pango
```

```yaml
custom:
  pythonRequirements:
    dockerFile: Dockerfile
    dockerizePip: true
    layer: true
    dockerExtraFiles:
      - /usr/lib64/libpango-1.0.so.0
      - /usr/lib64/libpango-1.0.so.0.2800.1

plugins:
  - serverless-python-requirements
```
