### ISSUE TITLE
Handle absolute children of flex boxes

### ISSUE THREAD

**Issue by daniel-butler** [Kozea/WeasyPrint#996]
Thank you for the amazing project! Because of this project I only have the problem below

Are there any gotcha's with `position: absolute`? I have not been able to get it to work. I was able to get bootstrap.css working with the pdf, but elements with the style of position `absolute` do not get rendered.

This is the custom css file
```css
div div#payment_method {
     position: absolute;
     font-weight: bolder;
     opacity: 80%;
     color: #3e1052;
}
```
 ..and the html
```html
<div class="row justify-content-center">
  <div
    id="payment_method"
    class="display-2"
  >
    <i>Paid by EFT</i>
</div>
```

The payment_method id is not rendered if `position: absolute` is displayed once I remove it the element is displayed, but the element is inline.
